/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.AbilityScore;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AbilityScoreRecord extends UpdatableRecordImpl<AbilityScoreRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 66874401;

    /**
     * Setter for <code>public.ability_score.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ability_score.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.ability_score.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ability_score.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.ability_score.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ability_score.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return AbilityScore.ABILITY_SCORE.ID;
    }

    @Override
    public Field<String> field2() {
        return AbilityScore.ABILITY_SCORE.NAME;
    }

    @Override
    public Field<String> field3() {
        return AbilityScore.ABILITY_SCORE.DESCRIPTION;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public AbilityScoreRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public AbilityScoreRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AbilityScoreRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public AbilityScoreRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AbilityScoreRecord
     */
    public AbilityScoreRecord() {
        super(AbilityScore.ABILITY_SCORE);
    }

    /**
     * Create a detached, initialised AbilityScoreRecord
     */
    public AbilityScoreRecord(String id, String name, String description) {
        super(AbilityScore.ABILITY_SCORE);

        set(0, id);
        set(1, name);
        set(2, description);
    }
}
