/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.AlchemistResearchField;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlchemistResearchFieldRecord extends UpdatableRecordImpl<AlchemistResearchFieldRecord> implements Record7<String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -1487866030;

    /**
     * Setter for <code>public.alchemist_research_field.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.alchemist_research_field.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.alchemist_research_field.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.alchemist_research_field.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.alchemist_research_field.field</code>.
     */
    public void setField(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.alchemist_research_field.field</code>.
     */
    public String getField() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.alchemist_research_field.infusions</code>.
     */
    public void setInfusions(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.alchemist_research_field.infusions</code>.
     */
    public String getInfusions() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.alchemist_research_field.potency</code>.
     */
    public void setPotency(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.alchemist_research_field.potency</code>.
     */
    public String getPotency() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.alchemist_research_field.greater_field</code>.
     */
    public void setGreaterField(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.alchemist_research_field.greater_field</code>.
     */
    public String getGreaterField() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.alchemist_research_field.perfection</code>.
     */
    public void setPerfection(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.alchemist_research_field.perfection</code>.
     */
    public String getPerfection() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return AlchemistResearchField.ALCHEMIST_RESEARCH_FIELD.ID;
    }

    @Override
    public Field<String> field2() {
        return AlchemistResearchField.ALCHEMIST_RESEARCH_FIELD.NAME;
    }

    @Override
    public Field<String> field3() {
        return AlchemistResearchField.ALCHEMIST_RESEARCH_FIELD.FIELD;
    }

    @Override
    public Field<String> field4() {
        return AlchemistResearchField.ALCHEMIST_RESEARCH_FIELD.INFUSIONS;
    }

    @Override
    public Field<String> field5() {
        return AlchemistResearchField.ALCHEMIST_RESEARCH_FIELD.POTENCY;
    }

    @Override
    public Field<String> field6() {
        return AlchemistResearchField.ALCHEMIST_RESEARCH_FIELD.GREATER_FIELD;
    }

    @Override
    public Field<String> field7() {
        return AlchemistResearchField.ALCHEMIST_RESEARCH_FIELD.PERFECTION;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getField();
    }

    @Override
    public String component4() {
        return getInfusions();
    }

    @Override
    public String component5() {
        return getPotency();
    }

    @Override
    public String component6() {
        return getGreaterField();
    }

    @Override
    public String component7() {
        return getPerfection();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getField();
    }

    @Override
    public String value4() {
        return getInfusions();
    }

    @Override
    public String value5() {
        return getPotency();
    }

    @Override
    public String value6() {
        return getGreaterField();
    }

    @Override
    public String value7() {
        return getPerfection();
    }

    @Override
    public AlchemistResearchFieldRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public AlchemistResearchFieldRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AlchemistResearchFieldRecord value3(String value) {
        setField(value);
        return this;
    }

    @Override
    public AlchemistResearchFieldRecord value4(String value) {
        setInfusions(value);
        return this;
    }

    @Override
    public AlchemistResearchFieldRecord value5(String value) {
        setPotency(value);
        return this;
    }

    @Override
    public AlchemistResearchFieldRecord value6(String value) {
        setGreaterField(value);
        return this;
    }

    @Override
    public AlchemistResearchFieldRecord value7(String value) {
        setPerfection(value);
        return this;
    }

    @Override
    public AlchemistResearchFieldRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlchemistResearchFieldRecord
     */
    public AlchemistResearchFieldRecord() {
        super(AlchemistResearchField.ALCHEMIST_RESEARCH_FIELD);
    }

    /**
     * Create a detached, initialised AlchemistResearchFieldRecord
     */
    public AlchemistResearchFieldRecord(String id, String name, String field, String infusions, String potency, String greaterField, String perfection) {
        super(AlchemistResearchField.ALCHEMIST_RESEARCH_FIELD);

        set(0, id);
        set(1, name);
        set(2, field);
        set(3, infusions);
        set(4, potency);
        set(5, greaterField);
        set(6, perfection);
    }
}
