/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.AncestryTrait;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AncestryTraitRecord extends UpdatableRecordImpl<AncestryTraitRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1421943892;

    /**
     * Setter for <code>public.ancestry_trait.ancestry_id</code>.
     */
    public void setAncestryId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ancestry_trait.ancestry_id</code>.
     */
    public String getAncestryId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.ancestry_trait.trait</code>.
     */
    public void setTrait(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ancestry_trait.trait</code>.
     */
    public String getTrait() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return AncestryTrait.ANCESTRY_TRAIT.ANCESTRY_ID;
    }

    @Override
    public Field<String> field2() {
        return AncestryTrait.ANCESTRY_TRAIT.TRAIT;
    }

    @Override
    public String component1() {
        return getAncestryId();
    }

    @Override
    public String component2() {
        return getTrait();
    }

    @Override
    public String value1() {
        return getAncestryId();
    }

    @Override
    public String value2() {
        return getTrait();
    }

    @Override
    public AncestryTraitRecord value1(String value) {
        setAncestryId(value);
        return this;
    }

    @Override
    public AncestryTraitRecord value2(String value) {
        setTrait(value);
        return this;
    }

    @Override
    public AncestryTraitRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AncestryTraitRecord
     */
    public AncestryTraitRecord() {
        super(AncestryTrait.ANCESTRY_TRAIT);
    }

    /**
     * Create a detached, initialised AncestryTraitRecord
     */
    public AncestryTraitRecord(String ancestryId, String trait) {
        super(AncestryTrait.ANCESTRY_TRAIT);

        set(0, ancestryId);
        set(1, trait);
    }
}
