/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.ArmorTrait;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArmorTraitRecord extends UpdatableRecordImpl<ArmorTraitRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1468774852;

    /**
     * Setter for <code>public.armor_trait.armor_id</code>.
     */
    public void setArmorId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.armor_trait.armor_id</code>.
     */
    public String getArmorId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.armor_trait.trait</code>.
     */
    public void setTrait(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.armor_trait.trait</code>.
     */
    public String getTrait() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ArmorTrait.ARMOR_TRAIT.ARMOR_ID;
    }

    @Override
    public Field<String> field2() {
        return ArmorTrait.ARMOR_TRAIT.TRAIT;
    }

    @Override
    public String component1() {
        return getArmorId();
    }

    @Override
    public String component2() {
        return getTrait();
    }

    @Override
    public String value1() {
        return getArmorId();
    }

    @Override
    public String value2() {
        return getTrait();
    }

    @Override
    public ArmorTraitRecord value1(String value) {
        setArmorId(value);
        return this;
    }

    @Override
    public ArmorTraitRecord value2(String value) {
        setTrait(value);
        return this;
    }

    @Override
    public ArmorTraitRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArmorTraitRecord
     */
    public ArmorTraitRecord() {
        super(ArmorTrait.ARMOR_TRAIT);
    }

    /**
     * Create a detached, initialised ArmorTraitRecord
     */
    public ArmorTraitRecord(String armorId, String trait) {
        super(ArmorTrait.ARMOR_TRAIT);

        set(0, armorId);
        set(1, trait);
    }
}
