/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.ArmorMaterial;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArmorMaterialRecord extends UpdatableRecordImpl<ArmorMaterialRecord> implements Record11<String, String, Integer, String, String, String, String, Integer, String, String, String> {

    private static final long serialVersionUID = -361022168;

    /**
     * Setter for <code>public.armor_material.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.armor_material.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.armor_material.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.armor_material.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.armor_material.level</code>.
     */
    public void setLevel(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.armor_material.level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.armor_material.reduces_bulk</code>.
     */
    public void setReducesBulk(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.armor_material.reduces_bulk</code>.
     */
    public String getReducesBulk() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.armor_material.strength_adj</code>.
     */
    public void setStrengthAdj(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.armor_material.strength_adj</code>.
     */
    public String getStrengthAdj() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.armor_material.speed</code>.
     */
    public void setSpeed(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.armor_material.speed</code>.
     */
    public String getSpeed() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.armor_material.ac</code>.
     */
    public void setAc(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.armor_material.ac</code>.
     */
    public String getAc() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.armor_material.base</code>.
     */
    public void setBase(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.armor_material.base</code>.
     */
    public Integer getBase() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.armor_material.description</code>.
     */
    public void setDescription(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.armor_material.description</code>.
     */
    public String getDescription() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.armor_material.src</code>.
     */
    public void setSrc(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.armor_material.src</code>.
     */
    public String getSrc() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.armor_material.url</code>.
     */
    public void setUrl(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.armor_material.url</code>.
     */
    public String getUrl() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<String, String, Integer, String, String, String, String, Integer, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<String, String, Integer, String, String, String, String, Integer, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ArmorMaterial.ARMOR_MATERIAL.ID;
    }

    @Override
    public Field<String> field2() {
        return ArmorMaterial.ARMOR_MATERIAL.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return ArmorMaterial.ARMOR_MATERIAL.LEVEL;
    }

    @Override
    public Field<String> field4() {
        return ArmorMaterial.ARMOR_MATERIAL.REDUCES_BULK;
    }

    @Override
    public Field<String> field5() {
        return ArmorMaterial.ARMOR_MATERIAL.STRENGTH_ADJ;
    }

    @Override
    public Field<String> field6() {
        return ArmorMaterial.ARMOR_MATERIAL.SPEED;
    }

    @Override
    public Field<String> field7() {
        return ArmorMaterial.ARMOR_MATERIAL.AC;
    }

    @Override
    public Field<Integer> field8() {
        return ArmorMaterial.ARMOR_MATERIAL.BASE;
    }

    @Override
    public Field<String> field9() {
        return ArmorMaterial.ARMOR_MATERIAL.DESCRIPTION;
    }

    @Override
    public Field<String> field10() {
        return ArmorMaterial.ARMOR_MATERIAL.SRC;
    }

    @Override
    public Field<String> field11() {
        return ArmorMaterial.ARMOR_MATERIAL.URL;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getLevel();
    }

    @Override
    public String component4() {
        return getReducesBulk();
    }

    @Override
    public String component5() {
        return getStrengthAdj();
    }

    @Override
    public String component6() {
        return getSpeed();
    }

    @Override
    public String component7() {
        return getAc();
    }

    @Override
    public Integer component8() {
        return getBase();
    }

    @Override
    public String component9() {
        return getDescription();
    }

    @Override
    public String component10() {
        return getSrc();
    }

    @Override
    public String component11() {
        return getUrl();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getLevel();
    }

    @Override
    public String value4() {
        return getReducesBulk();
    }

    @Override
    public String value5() {
        return getStrengthAdj();
    }

    @Override
    public String value6() {
        return getSpeed();
    }

    @Override
    public String value7() {
        return getAc();
    }

    @Override
    public Integer value8() {
        return getBase();
    }

    @Override
    public String value9() {
        return getDescription();
    }

    @Override
    public String value10() {
        return getSrc();
    }

    @Override
    public String value11() {
        return getUrl();
    }

    @Override
    public ArmorMaterialRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public ArmorMaterialRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ArmorMaterialRecord value3(Integer value) {
        setLevel(value);
        return this;
    }

    @Override
    public ArmorMaterialRecord value4(String value) {
        setReducesBulk(value);
        return this;
    }

    @Override
    public ArmorMaterialRecord value5(String value) {
        setStrengthAdj(value);
        return this;
    }

    @Override
    public ArmorMaterialRecord value6(String value) {
        setSpeed(value);
        return this;
    }

    @Override
    public ArmorMaterialRecord value7(String value) {
        setAc(value);
        return this;
    }

    @Override
    public ArmorMaterialRecord value8(Integer value) {
        setBase(value);
        return this;
    }

    @Override
    public ArmorMaterialRecord value9(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ArmorMaterialRecord value10(String value) {
        setSrc(value);
        return this;
    }

    @Override
    public ArmorMaterialRecord value11(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public ArmorMaterialRecord values(String value1, String value2, Integer value3, String value4, String value5, String value6, String value7, Integer value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArmorMaterialRecord
     */
    public ArmorMaterialRecord() {
        super(ArmorMaterial.ARMOR_MATERIAL);
    }

    /**
     * Create a detached, initialised ArmorMaterialRecord
     */
    public ArmorMaterialRecord(String id, String name, Integer level, String reducesBulk, String strengthAdj, String speed, String ac, Integer base, String description, String src, String url) {
        super(ArmorMaterial.ARMOR_MATERIAL);

        set(0, id);
        set(1, name);
        set(2, level);
        set(3, reducesBulk);
        set(4, strengthAdj);
        set(5, speed);
        set(6, ac);
        set(7, base);
        set(8, description);
        set(9, src);
        set(10, url);
    }
}
