/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.CompanionItemTrait;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanionItemTraitRecord extends UpdatableRecordImpl<CompanionItemTraitRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1712154289;

    /**
     * Setter for <code>public.companion_item_trait.companion_item_id</code>.
     */
    public void setCompanionItemId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.companion_item_trait.companion_item_id</code>.
     */
    public String getCompanionItemId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.companion_item_trait.trait</code>.
     */
    public void setTrait(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.companion_item_trait.trait</code>.
     */
    public String getTrait() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return CompanionItemTrait.COMPANION_ITEM_TRAIT.COMPANION_ITEM_ID;
    }

    @Override
    public Field<String> field2() {
        return CompanionItemTrait.COMPANION_ITEM_TRAIT.TRAIT;
    }

    @Override
    public String component1() {
        return getCompanionItemId();
    }

    @Override
    public String component2() {
        return getTrait();
    }

    @Override
    public String value1() {
        return getCompanionItemId();
    }

    @Override
    public String value2() {
        return getTrait();
    }

    @Override
    public CompanionItemTraitRecord value1(String value) {
        setCompanionItemId(value);
        return this;
    }

    @Override
    public CompanionItemTraitRecord value2(String value) {
        setTrait(value);
        return this;
    }

    @Override
    public CompanionItemTraitRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanionItemTraitRecord
     */
    public CompanionItemTraitRecord() {
        super(CompanionItemTrait.COMPANION_ITEM_TRAIT);
    }

    /**
     * Create a detached, initialised CompanionItemTraitRecord
     */
    public CompanionItemTraitRecord(String companionItemId, String trait) {
        super(CompanionItemTrait.COMPANION_ITEM_TRAIT);

        set(0, companionItemId);
        set(1, trait);
    }
}
