/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.CreatureSize;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CreatureSizeRecord extends UpdatableRecordImpl<CreatureSizeRecord> implements Record5<String, String, String, String, String> {

    private static final long serialVersionUID = -80811305;

    /**
     * Setter for <code>public.creature_size.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.creature_size.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.creature_size.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.creature_size.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.creature_size.space</code>.
     */
    public void setSpace(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.creature_size.space</code>.
     */
    public String getSpace() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.creature_size.reach_tall</code>.
     */
    public void setReachTall(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.creature_size.reach_tall</code>.
     */
    public String getReachTall() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.creature_size.reach_long</code>.
     */
    public void setReachLong(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.creature_size.reach_long</code>.
     */
    public String getReachLong() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return CreatureSize.CREATURE_SIZE.ID;
    }

    @Override
    public Field<String> field2() {
        return CreatureSize.CREATURE_SIZE.NAME;
    }

    @Override
    public Field<String> field3() {
        return CreatureSize.CREATURE_SIZE.SPACE;
    }

    @Override
    public Field<String> field4() {
        return CreatureSize.CREATURE_SIZE.REACH_TALL;
    }

    @Override
    public Field<String> field5() {
        return CreatureSize.CREATURE_SIZE.REACH_LONG;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getSpace();
    }

    @Override
    public String component4() {
        return getReachTall();
    }

    @Override
    public String component5() {
        return getReachLong();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getSpace();
    }

    @Override
    public String value4() {
        return getReachTall();
    }

    @Override
    public String value5() {
        return getReachLong();
    }

    @Override
    public CreatureSizeRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public CreatureSizeRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CreatureSizeRecord value3(String value) {
        setSpace(value);
        return this;
    }

    @Override
    public CreatureSizeRecord value4(String value) {
        setReachTall(value);
        return this;
    }

    @Override
    public CreatureSizeRecord value5(String value) {
        setReachLong(value);
        return this;
    }

    @Override
    public CreatureSizeRecord values(String value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CreatureSizeRecord
     */
    public CreatureSizeRecord() {
        super(CreatureSize.CREATURE_SIZE);
    }

    /**
     * Create a detached, initialised CreatureSizeRecord
     */
    public CreatureSizeRecord(String id, String name, String space, String reachTall, String reachLong) {
        super(CreatureSize.CREATURE_SIZE);

        set(0, id);
        set(1, name);
        set(2, space);
        set(3, reachTall);
        set(4, reachLong);
    }
}
