/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.FeatTrait;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeatTraitRecord extends UpdatableRecordImpl<FeatTraitRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 160139224;

    /**
     * Setter for <code>public.feat_trait.feat_id</code>.
     */
    public void setFeatId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.feat_trait.feat_id</code>.
     */
    public String getFeatId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.feat_trait.trait</code>.
     */
    public void setTrait(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.feat_trait.trait</code>.
     */
    public String getTrait() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return FeatTrait.FEAT_TRAIT.FEAT_ID;
    }

    @Override
    public Field<String> field2() {
        return FeatTrait.FEAT_TRAIT.TRAIT;
    }

    @Override
    public String component1() {
        return getFeatId();
    }

    @Override
    public String component2() {
        return getTrait();
    }

    @Override
    public String value1() {
        return getFeatId();
    }

    @Override
    public String value2() {
        return getTrait();
    }

    @Override
    public FeatTraitRecord value1(String value) {
        setFeatId(value);
        return this;
    }

    @Override
    public FeatTraitRecord value2(String value) {
        setTrait(value);
        return this;
    }

    @Override
    public FeatTraitRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeatTraitRecord
     */
    public FeatTraitRecord() {
        super(FeatTrait.FEAT_TRAIT);
    }

    /**
     * Create a detached, initialised FeatTraitRecord
     */
    public FeatTraitRecord(String featId, String trait) {
        super(FeatTrait.FEAT_TRAIT);

        set(0, featId);
        set(1, trait);
    }
}
