/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.FeatAnimalCompanionRequirement;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeatAnimalCompanionRequirementRecord extends UpdatableRecordImpl<FeatAnimalCompanionRequirementRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1921834031;

    /**
     * Setter for <code>public.feat_animal_companion_requirement.feat_id</code>.
     */
    public void setFeatId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.feat_animal_companion_requirement.feat_id</code>.
     */
    public String getFeatId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.feat_animal_companion_requirement.feat_category</code>.
     */
    public void setFeatCategory(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.feat_animal_companion_requirement.feat_category</code>.
     */
    public String getFeatCategory() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return FeatAnimalCompanionRequirement.FEAT_ANIMAL_COMPANION_REQUIREMENT.FEAT_ID;
    }

    @Override
    public Field<String> field2() {
        return FeatAnimalCompanionRequirement.FEAT_ANIMAL_COMPANION_REQUIREMENT.FEAT_CATEGORY;
    }

    @Override
    public String component1() {
        return getFeatId();
    }

    @Override
    public String component2() {
        return getFeatCategory();
    }

    @Override
    public String value1() {
        return getFeatId();
    }

    @Override
    public String value2() {
        return getFeatCategory();
    }

    @Override
    public FeatAnimalCompanionRequirementRecord value1(String value) {
        setFeatId(value);
        return this;
    }

    @Override
    public FeatAnimalCompanionRequirementRecord value2(String value) {
        setFeatCategory(value);
        return this;
    }

    @Override
    public FeatAnimalCompanionRequirementRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeatAnimalCompanionRequirementRecord
     */
    public FeatAnimalCompanionRequirementRecord() {
        super(FeatAnimalCompanionRequirement.FEAT_ANIMAL_COMPANION_REQUIREMENT);
    }

    /**
     * Create a detached, initialised FeatAnimalCompanionRequirementRecord
     */
    public FeatAnimalCompanionRequirementRecord(String featId, String featCategory) {
        super(FeatAnimalCompanionRequirement.FEAT_ANIMAL_COMPANION_REQUIREMENT);

        set(0, featId);
        set(1, featCategory);
    }
}
