/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.FeatMagicRequirement;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeatMagicRequirementRecord extends UpdatableRecordImpl<FeatMagicRequirementRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -248989044;

    /**
     * Setter for <code>public.feat_magic_requirement.feat_id</code>.
     */
    public void setFeatId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.feat_magic_requirement.feat_id</code>.
     */
    public String getFeatId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.feat_magic_requirement.training_level_id</code>.
     */
    public void setTrainingLevelId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.feat_magic_requirement.training_level_id</code>.
     */
    public String getTrainingLevelId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return FeatMagicRequirement.FEAT_MAGIC_REQUIREMENT.FEAT_ID;
    }

    @Override
    public Field<String> field2() {
        return FeatMagicRequirement.FEAT_MAGIC_REQUIREMENT.TRAINING_LEVEL_ID;
    }

    @Override
    public String component1() {
        return getFeatId();
    }

    @Override
    public String component2() {
        return getTrainingLevelId();
    }

    @Override
    public String value1() {
        return getFeatId();
    }

    @Override
    public String value2() {
        return getTrainingLevelId();
    }

    @Override
    public FeatMagicRequirementRecord value1(String value) {
        setFeatId(value);
        return this;
    }

    @Override
    public FeatMagicRequirementRecord value2(String value) {
        setTrainingLevelId(value);
        return this;
    }

    @Override
    public FeatMagicRequirementRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeatMagicRequirementRecord
     */
    public FeatMagicRequirementRecord() {
        super(FeatMagicRequirement.FEAT_MAGIC_REQUIREMENT);
    }

    /**
     * Create a detached, initialised FeatMagicRequirementRecord
     */
    public FeatMagicRequirementRecord(String featId, String trainingLevelId) {
        super(FeatMagicRequirement.FEAT_MAGIC_REQUIREMENT);

        set(0, featId);
        set(1, trainingLevelId);
    }
}
