/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.FeatFamiliarRequirement;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeatFamiliarRequirementRecord extends UpdatableRecordImpl<FeatFamiliarRequirementRecord> implements Record1<String> {

    private static final long serialVersionUID = 91687708;

    /**
     * Setter for <code>public.feat_familiar_requirement.feat_id</code>.
     */
    public void setFeatId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.feat_familiar_requirement.feat_id</code>.
     */
    public String getFeatId() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return FeatFamiliarRequirement.FEAT_FAMILIAR_REQUIREMENT.FEAT_ID;
    }

    @Override
    public String component1() {
        return getFeatId();
    }

    @Override
    public String value1() {
        return getFeatId();
    }

    @Override
    public FeatFamiliarRequirementRecord value1(String value) {
        setFeatId(value);
        return this;
    }

    @Override
    public FeatFamiliarRequirementRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeatFamiliarRequirementRecord
     */
    public FeatFamiliarRequirementRecord() {
        super(FeatFamiliarRequirement.FEAT_FAMILIAR_REQUIREMENT);
    }

    /**
     * Create a detached, initialised FeatFamiliarRequirementRecord
     */
    public FeatFamiliarRequirementRecord(String featId) {
        super(FeatFamiliarRequirement.FEAT_FAMILIAR_REQUIREMENT);

        set(0, featId);
    }
}
