/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.FeatFeatRequirement;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeatFeatRequirementRecord extends UpdatableRecordImpl<FeatFeatRequirementRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1679568824;

    /**
     * Setter for <code>public.feat_feat_requirement.feat_id</code>.
     */
    public void setFeatId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.feat_feat_requirement.feat_id</code>.
     */
    public String getFeatId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.feat_feat_requirement.required_feat_id</code>.
     */
    public void setRequiredFeatId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.feat_feat_requirement.required_feat_id</code>.
     */
    public String getRequiredFeatId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return FeatFeatRequirement.FEAT_FEAT_REQUIREMENT.FEAT_ID;
    }

    @Override
    public Field<String> field2() {
        return FeatFeatRequirement.FEAT_FEAT_REQUIREMENT.REQUIRED_FEAT_ID;
    }

    @Override
    public String component1() {
        return getFeatId();
    }

    @Override
    public String component2() {
        return getRequiredFeatId();
    }

    @Override
    public String value1() {
        return getFeatId();
    }

    @Override
    public String value2() {
        return getRequiredFeatId();
    }

    @Override
    public FeatFeatRequirementRecord value1(String value) {
        setFeatId(value);
        return this;
    }

    @Override
    public FeatFeatRequirementRecord value2(String value) {
        setRequiredFeatId(value);
        return this;
    }

    @Override
    public FeatFeatRequirementRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeatFeatRequirementRecord
     */
    public FeatFeatRequirementRecord() {
        super(FeatFeatRequirement.FEAT_FEAT_REQUIREMENT);
    }

    /**
     * Create a detached, initialised FeatFeatRequirementRecord
     */
    public FeatFeatRequirementRecord(String featId, String requiredFeatId) {
        super(FeatFeatRequirement.FEAT_FEAT_REQUIREMENT);

        set(0, featId);
        set(1, requiredFeatId);
    }
}
