/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.ItemTrait;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemTraitRecord extends UpdatableRecordImpl<ItemTraitRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -823173604;

    /**
     * Setter for <code>public.item_trait.item_id</code>.
     */
    public void setItemId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.item_trait.item_id</code>.
     */
    public String getItemId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.item_trait.trait</code>.
     */
    public void setTrait(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.item_trait.trait</code>.
     */
    public String getTrait() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ItemTrait.ITEM_TRAIT.ITEM_ID;
    }

    @Override
    public Field<String> field2() {
        return ItemTrait.ITEM_TRAIT.TRAIT;
    }

    @Override
    public String component1() {
        return getItemId();
    }

    @Override
    public String component2() {
        return getTrait();
    }

    @Override
    public String value1() {
        return getItemId();
    }

    @Override
    public String value2() {
        return getTrait();
    }

    @Override
    public ItemTraitRecord value1(String value) {
        setItemId(value);
        return this;
    }

    @Override
    public ItemTraitRecord value2(String value) {
        setTrait(value);
        return this;
    }

    @Override
    public ItemTraitRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemTraitRecord
     */
    public ItemTraitRecord() {
        super(ItemTrait.ITEM_TRAIT);
    }

    /**
     * Create a detached, initialised ItemTraitRecord
     */
    public ItemTraitRecord(String itemId, String trait) {
        super(ItemTrait.ITEM_TRAIT);

        set(0, itemId);
        set(1, trait);
    }
}
