/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.Item;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemRecord extends UpdatableRecordImpl<ItemRecord> implements Record18<String, String, String, Short, Short, BigDecimal, String, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 537920077;

    /**
     * Setter for <code>public.item.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.item.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.item.category</code>.
     */
    public void setCategory(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.item.category</code>.
     */
    public String getCategory() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.item.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.item.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.item.level</code>.
     */
    public void setLevel(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.item.level</code>.
     */
    public Short getLevel() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.item.actions</code>.
     */
    public void setActions(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.item.actions</code>.
     */
    public Short getActions() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.item.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.item.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.item.hands</code>.
     */
    public void setHands(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.item.hands</code>.
     */
    public String getHands() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.item.bulk</code>.
     */
    public void setBulk(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.item.bulk</code>.
     */
    public String getBulk() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.item.contains</code>.
     */
    public void setContains(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.item.contains</code>.
     */
    public String getContains() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.item.usage</code>.
     */
    public void setUsage(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.item.usage</code>.
     */
    public String getUsage() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.item.amount</code>.
     */
    public void setAmount(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.item.amount</code>.
     */
    public String getAmount() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.item.action0</code>.
     */
    public void setAction0(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.item.action0</code>.
     */
    public String getAction0() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.item.action0desc</code>.
     */
    public void setAction0desc(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.item.action0desc</code>.
     */
    public String getAction0desc() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.item.action1</code>.
     */
    public void setAction1(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.item.action1</code>.
     */
    public String getAction1() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.item.action1desc</code>.
     */
    public void setAction1desc(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.item.action1desc</code>.
     */
    public String getAction1desc() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.item.description</code>.
     */
    public void setDescription(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.item.description</code>.
     */
    public String getDescription() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.item.src</code>.
     */
    public void setSrc(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.item.src</code>.
     */
    public String getSrc() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.item.url</code>.
     */
    public void setUrl(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.item.url</code>.
     */
    public String getUrl() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<String, String, String, Short, Short, BigDecimal, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<String, String, String, Short, Short, BigDecimal, String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Item.ITEM.ID;
    }

    @Override
    public Field<String> field2() {
        return Item.ITEM.CATEGORY;
    }

    @Override
    public Field<String> field3() {
        return Item.ITEM.NAME;
    }

    @Override
    public Field<Short> field4() {
        return Item.ITEM.LEVEL;
    }

    @Override
    public Field<Short> field5() {
        return Item.ITEM.ACTIONS;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Item.ITEM.PRICE;
    }

    @Override
    public Field<String> field7() {
        return Item.ITEM.HANDS;
    }

    @Override
    public Field<String> field8() {
        return Item.ITEM.BULK;
    }

    @Override
    public Field<String> field9() {
        return Item.ITEM.CONTAINS;
    }

    @Override
    public Field<String> field10() {
        return Item.ITEM.USAGE;
    }

    @Override
    public Field<String> field11() {
        return Item.ITEM.AMOUNT;
    }

    @Override
    public Field<String> field12() {
        return Item.ITEM.ACTION0;
    }

    @Override
    public Field<String> field13() {
        return Item.ITEM.ACTION0DESC;
    }

    @Override
    public Field<String> field14() {
        return Item.ITEM.ACTION1;
    }

    @Override
    public Field<String> field15() {
        return Item.ITEM.ACTION1DESC;
    }

    @Override
    public Field<String> field16() {
        return Item.ITEM.DESCRIPTION;
    }

    @Override
    public Field<String> field17() {
        return Item.ITEM.SRC;
    }

    @Override
    public Field<String> field18() {
        return Item.ITEM.URL;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCategory();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Short component4() {
        return getLevel();
    }

    @Override
    public Short component5() {
        return getActions();
    }

    @Override
    public BigDecimal component6() {
        return getPrice();
    }

    @Override
    public String component7() {
        return getHands();
    }

    @Override
    public String component8() {
        return getBulk();
    }

    @Override
    public String component9() {
        return getContains();
    }

    @Override
    public String component10() {
        return getUsage();
    }

    @Override
    public String component11() {
        return getAmount();
    }

    @Override
    public String component12() {
        return getAction0();
    }

    @Override
    public String component13() {
        return getAction0desc();
    }

    @Override
    public String component14() {
        return getAction1();
    }

    @Override
    public String component15() {
        return getAction1desc();
    }

    @Override
    public String component16() {
        return getDescription();
    }

    @Override
    public String component17() {
        return getSrc();
    }

    @Override
    public String component18() {
        return getUrl();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCategory();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Short value4() {
        return getLevel();
    }

    @Override
    public Short value5() {
        return getActions();
    }

    @Override
    public BigDecimal value6() {
        return getPrice();
    }

    @Override
    public String value7() {
        return getHands();
    }

    @Override
    public String value8() {
        return getBulk();
    }

    @Override
    public String value9() {
        return getContains();
    }

    @Override
    public String value10() {
        return getUsage();
    }

    @Override
    public String value11() {
        return getAmount();
    }

    @Override
    public String value12() {
        return getAction0();
    }

    @Override
    public String value13() {
        return getAction0desc();
    }

    @Override
    public String value14() {
        return getAction1();
    }

    @Override
    public String value15() {
        return getAction1desc();
    }

    @Override
    public String value16() {
        return getDescription();
    }

    @Override
    public String value17() {
        return getSrc();
    }

    @Override
    public String value18() {
        return getUrl();
    }

    @Override
    public ItemRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public ItemRecord value2(String value) {
        setCategory(value);
        return this;
    }

    @Override
    public ItemRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ItemRecord value4(Short value) {
        setLevel(value);
        return this;
    }

    @Override
    public ItemRecord value5(Short value) {
        setActions(value);
        return this;
    }

    @Override
    public ItemRecord value6(BigDecimal value) {
        setPrice(value);
        return this;
    }

    @Override
    public ItemRecord value7(String value) {
        setHands(value);
        return this;
    }

    @Override
    public ItemRecord value8(String value) {
        setBulk(value);
        return this;
    }

    @Override
    public ItemRecord value9(String value) {
        setContains(value);
        return this;
    }

    @Override
    public ItemRecord value10(String value) {
        setUsage(value);
        return this;
    }

    @Override
    public ItemRecord value11(String value) {
        setAmount(value);
        return this;
    }

    @Override
    public ItemRecord value12(String value) {
        setAction0(value);
        return this;
    }

    @Override
    public ItemRecord value13(String value) {
        setAction0desc(value);
        return this;
    }

    @Override
    public ItemRecord value14(String value) {
        setAction1(value);
        return this;
    }

    @Override
    public ItemRecord value15(String value) {
        setAction1desc(value);
        return this;
    }

    @Override
    public ItemRecord value16(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ItemRecord value17(String value) {
        setSrc(value);
        return this;
    }

    @Override
    public ItemRecord value18(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public ItemRecord values(String value1, String value2, String value3, Short value4, Short value5, BigDecimal value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17, String value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemRecord
     */
    public ItemRecord() {
        super(Item.ITEM);
    }

    /**
     * Create a detached, initialised ItemRecord
     */
    public ItemRecord(String id, String category, String name, Short level, Short actions, BigDecimal price, String hands, String bulk, String contains, String usage, String amount, String action0, String action0desc, String action1, String action1desc, String description, String src, String url) {
        super(Item.ITEM);

        set(0, id);
        set(1, category);
        set(2, name);
        set(3, level);
        set(4, actions);
        set(5, price);
        set(6, hands);
        set(7, bulk);
        set(8, contains);
        set(9, usage);
        set(10, amount);
        set(11, action0);
        set(12, action0desc);
        set(13, action1);
        set(14, action1desc);
        set(15, description);
        set(16, src);
        set(17, url);
    }
}
