/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.Language;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LanguageRecord extends UpdatableRecordImpl<LanguageRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = -1985353111;

    /**
     * Setter for <code>public.language.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.language.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.language.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.language.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.language.spoken_by</code>.
     */
    public void setSpokenBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.language.spoken_by</code>.
     */
    public String getSpokenBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.language.category_id</code>.
     */
    public void setCategoryId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.language.category_id</code>.
     */
    public String getCategoryId() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Language.LANGUAGE.ID;
    }

    @Override
    public Field<String> field2() {
        return Language.LANGUAGE.NAME;
    }

    @Override
    public Field<String> field3() {
        return Language.LANGUAGE.SPOKEN_BY;
    }

    @Override
    public Field<String> field4() {
        return Language.LANGUAGE.CATEGORY_ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getSpokenBy();
    }

    @Override
    public String component4() {
        return getCategoryId();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getSpokenBy();
    }

    @Override
    public String value4() {
        return getCategoryId();
    }

    @Override
    public LanguageRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public LanguageRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public LanguageRecord value3(String value) {
        setSpokenBy(value);
        return this;
    }

    @Override
    public LanguageRecord value4(String value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public LanguageRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LanguageRecord
     */
    public LanguageRecord() {
        super(Language.LANGUAGE);
    }

    /**
     * Create a detached, initialised LanguageRecord
     */
    public LanguageRecord(String id, String name, String spokenBy, String categoryId) {
        super(Language.LANGUAGE);

        set(0, id);
        set(1, name);
        set(2, spokenBy);
        set(3, categoryId);
    }
}
