/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.MagicWeaponTrait;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MagicWeaponTraitRecord extends UpdatableRecordImpl<MagicWeaponTraitRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -7127743;

    /**
     * Setter for <code>public.magic_weapon_trait.magic_weapon_id</code>.
     */
    public void setMagicWeaponId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.magic_weapon_trait.magic_weapon_id</code>.
     */
    public String getMagicWeaponId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.magic_weapon_trait.trait</code>.
     */
    public void setTrait(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.magic_weapon_trait.trait</code>.
     */
    public String getTrait() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return MagicWeaponTrait.MAGIC_WEAPON_TRAIT.MAGIC_WEAPON_ID;
    }

    @Override
    public Field<String> field2() {
        return MagicWeaponTrait.MAGIC_WEAPON_TRAIT.TRAIT;
    }

    @Override
    public String component1() {
        return getMagicWeaponId();
    }

    @Override
    public String component2() {
        return getTrait();
    }

    @Override
    public String value1() {
        return getMagicWeaponId();
    }

    @Override
    public String value2() {
        return getTrait();
    }

    @Override
    public MagicWeaponTraitRecord value1(String value) {
        setMagicWeaponId(value);
        return this;
    }

    @Override
    public MagicWeaponTraitRecord value2(String value) {
        setTrait(value);
        return this;
    }

    @Override
    public MagicWeaponTraitRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MagicWeaponTraitRecord
     */
    public MagicWeaponTraitRecord() {
        super(MagicWeaponTrait.MAGIC_WEAPON_TRAIT);
    }

    /**
     * Create a detached, initialised MagicWeaponTraitRecord
     */
    public MagicWeaponTraitRecord(String magicWeaponId, String trait) {
        super(MagicWeaponTrait.MAGIC_WEAPON_TRAIT);

        set(0, magicWeaponId);
        set(1, trait);
    }
}
