/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.PetAbility;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PetAbilityRecord extends UpdatableRecordImpl<PetAbilityRecord> implements Record6<String, String, Integer, String, String, String> {

    private static final long serialVersionUID = -1920337027;

    /**
     * Setter for <code>public.pet_ability.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pet_ability.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.pet_ability.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pet_ability.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.pet_ability.type</code>.
     */
    public void setType(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pet_ability.type</code>.
     */
    public Integer getType() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.pet_ability.reqs</code>.
     */
    public void setReqs(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.pet_ability.reqs</code>.
     */
    public String getReqs() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.pet_ability.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.pet_ability.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.pet_ability.src</code>.
     */
    public void setSrc(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.pet_ability.src</code>.
     */
    public String getSrc() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, Integer, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, Integer, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return PetAbility.PET_ABILITY.ID;
    }

    @Override
    public Field<String> field2() {
        return PetAbility.PET_ABILITY.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return PetAbility.PET_ABILITY.TYPE;
    }

    @Override
    public Field<String> field4() {
        return PetAbility.PET_ABILITY.REQS;
    }

    @Override
    public Field<String> field5() {
        return PetAbility.PET_ABILITY.DESCRIPTION;
    }

    @Override
    public Field<String> field6() {
        return PetAbility.PET_ABILITY.SRC;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getType();
    }

    @Override
    public String component4() {
        return getReqs();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public String component6() {
        return getSrc();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getType();
    }

    @Override
    public String value4() {
        return getReqs();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public String value6() {
        return getSrc();
    }

    @Override
    public PetAbilityRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public PetAbilityRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PetAbilityRecord value3(Integer value) {
        setType(value);
        return this;
    }

    @Override
    public PetAbilityRecord value4(String value) {
        setReqs(value);
        return this;
    }

    @Override
    public PetAbilityRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public PetAbilityRecord value6(String value) {
        setSrc(value);
        return this;
    }

    @Override
    public PetAbilityRecord values(String value1, String value2, Integer value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PetAbilityRecord
     */
    public PetAbilityRecord() {
        super(PetAbility.PET_ABILITY);
    }

    /**
     * Create a detached, initialised PetAbilityRecord
     */
    public PetAbilityRecord(String id, String name, Integer type, String reqs, String description, String src) {
        super(PetAbility.PET_ABILITY);

        set(0, id);
        set(1, name);
        set(2, type);
        set(3, reqs);
        set(4, description);
        set(5, src);
    }
}
