/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.PetAnimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PetAnimalRecord extends UpdatableRecordImpl<PetAnimalRecord> {

    private static final long serialVersionUID = -1999820115;

    /**
     * Setter for <code>public.pet_animal.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pet_animal.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.pet_animal.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pet_animal.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.pet_animal.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pet_animal.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.pet_animal.size</code>.
     */
    public void setSize(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.pet_animal.size</code>.
     */
    public String getSize() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.pet_animal.larger</code>.
     */
    public void setLarger(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.pet_animal.larger</code>.
     */
    public String getLarger() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.pet_animal.melee1</code>.
     */
    public void setMelee1(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.pet_animal.melee1</code>.
     */
    public String getMelee1() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.pet_animal.melee1Action</code>.
     */
    public void setMelee1action(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.pet_animal.melee1Action</code>.
     */
    public Integer getMelee1action() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.pet_animal.melee1Dam</code>.
     */
    public void setMelee1dam(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.pet_animal.melee1Dam</code>.
     */
    public String getMelee1dam() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.pet_animal.melee1Type</code>.
     */
    public void setMelee1type(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.pet_animal.melee1Type</code>.
     */
    public String getMelee1type() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.pet_animal.melee2</code>.
     */
    public void setMelee2(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.pet_animal.melee2</code>.
     */
    public String getMelee2() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.pet_animal.melee2Action</code>.
     */
    public void setMelee2action(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.pet_animal.melee2Action</code>.
     */
    public String getMelee2action() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.pet_animal.melee2Dam</code>.
     */
    public void setMelee2dam(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.pet_animal.melee2Dam</code>.
     */
    public String getMelee2dam() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.pet_animal.melee2Type</code>.
     */
    public void setMelee2type(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.pet_animal.melee2Type</code>.
     */
    public String getMelee2type() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.pet_animal.str</code>.
     */
    public void setStr(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.pet_animal.str</code>.
     */
    public Integer getStr() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.pet_animal.dex</code>.
     */
    public void setDex(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.pet_animal.dex</code>.
     */
    public Integer getDex() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.pet_animal.con</code>.
     */
    public void setCon(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.pet_animal.con</code>.
     */
    public Integer getCon() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.pet_animal.intel</code>.
     */
    public void setIntel(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.pet_animal.intel</code>.
     */
    public Integer getIntel() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>public.pet_animal.wis</code>.
     */
    public void setWis(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.pet_animal.wis</code>.
     */
    public Integer getWis() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.pet_animal.cha</code>.
     */
    public void setCha(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.pet_animal.cha</code>.
     */
    public Integer getCha() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>public.pet_animal.hp</code>.
     */
    public void setHp(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.pet_animal.hp</code>.
     */
    public Integer getHp() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>public.pet_animal.skill</code>.
     */
    public void setSkill(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.pet_animal.skill</code>.
     */
    public String getSkill() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.pet_animal.senses</code>.
     */
    public void setSenses(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.pet_animal.senses</code>.
     */
    public String getSenses() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.pet_animal.speed</code>.
     */
    public void setSpeed(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.pet_animal.speed</code>.
     */
    public Integer getSpeed() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>public.pet_animal.burrow</code>.
     */
    public void setBurrow(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.pet_animal.burrow</code>.
     */
    public String getBurrow() {
        return (String) get(23);
    }

    /**
     * Setter for <code>public.pet_animal.climb</code>.
     */
    public void setClimb(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.pet_animal.climb</code>.
     */
    public String getClimb() {
        return (String) get(24);
    }

    /**
     * Setter for <code>public.pet_animal.swim</code>.
     */
    public void setSwim(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.pet_animal.swim</code>.
     */
    public String getSwim() {
        return (String) get(25);
    }

    /**
     * Setter for <code>public.pet_animal.fly</code>.
     */
    public void setFly(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.pet_animal.fly</code>.
     */
    public String getFly() {
        return (String) get(26);
    }

    /**
     * Setter for <code>public.pet_animal.special</code>.
     */
    public void setSpecial(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.pet_animal.special</code>.
     */
    public String getSpecial() {
        return (String) get(27);
    }

    /**
     * Setter for <code>public.pet_animal.support</code>.
     */
    public void setSupport(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.pet_animal.support</code>.
     */
    public String getSupport() {
        return (String) get(28);
    }

    /**
     * Setter for <code>public.pet_animal.adv_name</code>.
     */
    public void setAdvName(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.pet_animal.adv_name</code>.
     */
    public String getAdvName() {
        return (String) get(29);
    }

    /**
     * Setter for <code>public.pet_animal.adv_action</code>.
     */
    public void setAdvAction(Integer value) {
        set(30, value);
    }

    /**
     * Getter for <code>public.pet_animal.adv_action</code>.
     */
    public Integer getAdvAction() {
        return (Integer) get(30);
    }

    /**
     * Setter for <code>public.pet_animal.adv_traits</code>.
     */
    public void setAdvTraits(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>public.pet_animal.adv_traits</code>.
     */
    public String getAdvTraits() {
        return (String) get(31);
    }

    /**
     * Setter for <code>public.pet_animal.adv_desc</code>.
     */
    public void setAdvDesc(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>public.pet_animal.adv_desc</code>.
     */
    public String getAdvDesc() {
        return (String) get(32);
    }

    /**
     * Setter for <code>public.pet_animal.src</code>.
     */
    public void setSrc(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>public.pet_animal.src</code>.
     */
    public String getSrc() {
        return (String) get(33);
    }

    /**
     * Setter for <code>public.pet_animal.url</code>.
     */
    public void setUrl(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>public.pet_animal.url</code>.
     */
    public String getUrl() {
        return (String) get(34);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PetAnimalRecord
     */
    public PetAnimalRecord() {
        super(PetAnimal.PET_ANIMAL);
    }

    /**
     * Create a detached, initialised PetAnimalRecord
     */
    public PetAnimalRecord(String id, String name, String description, String size, String larger, String melee1, Integer melee1action, String melee1dam, String melee1type, String melee2, String melee2action, String melee2dam, String melee2type, Integer str, Integer dex, Integer con, Integer intel, Integer wis, Integer cha, Integer hp, String skill, String senses, Integer speed, String burrow, String climb, String swim, String fly, String special, String support, String advName, Integer advAction, String advTraits, String advDesc, String src, String url) {
        super(PetAnimal.PET_ANIMAL);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, size);
        set(4, larger);
        set(5, melee1);
        set(6, melee1action);
        set(7, melee1dam);
        set(8, melee1type);
        set(9, melee2);
        set(10, melee2action);
        set(11, melee2dam);
        set(12, melee2type);
        set(13, str);
        set(14, dex);
        set(15, con);
        set(16, intel);
        set(17, wis);
        set(18, cha);
        set(19, hp);
        set(20, skill);
        set(21, senses);
        set(22, speed);
        set(23, burrow);
        set(24, climb);
        set(25, swim);
        set(26, fly);
        set(27, special);
        set(28, support);
        set(29, advName);
        set(30, advAction);
        set(31, advTraits);
        set(32, advDesc);
        set(33, src);
        set(34, url);
    }
}
