/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.RulesSource;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RulesSourceRecord extends UpdatableRecordImpl<RulesSourceRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 499601181;

    /**
     * Setter for <code>public.rules_source.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.rules_source.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.rules_source.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.rules_source.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.rules_source.url</code>.
     */
    public void setUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.rules_source.url</code>.
     */
    public String getUrl() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return RulesSource.RULES_SOURCE.ID;
    }

    @Override
    public Field<String> field2() {
        return RulesSource.RULES_SOURCE.NAME;
    }

    @Override
    public Field<String> field3() {
        return RulesSource.RULES_SOURCE.URL;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getUrl();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getUrl();
    }

    @Override
    public RulesSourceRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public RulesSourceRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public RulesSourceRecord value3(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public RulesSourceRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RulesSourceRecord
     */
    public RulesSourceRecord() {
        super(RulesSource.RULES_SOURCE);
    }

    /**
     * Create a detached, initialised RulesSourceRecord
     */
    public RulesSourceRecord(String id, String name, String url) {
        super(RulesSource.RULES_SOURCE);

        set(0, id);
        set(1, name);
        set(2, url);
    }
}
