/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.ShieldTrait;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShieldTraitRecord extends UpdatableRecordImpl<ShieldTraitRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -111098636;

    /**
     * Setter for <code>public.shield_trait.shield_id</code>.
     */
    public void setShieldId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.shield_trait.shield_id</code>.
     */
    public String getShieldId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.shield_trait.trait</code>.
     */
    public void setTrait(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.shield_trait.trait</code>.
     */
    public String getTrait() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ShieldTrait.SHIELD_TRAIT.SHIELD_ID;
    }

    @Override
    public Field<String> field2() {
        return ShieldTrait.SHIELD_TRAIT.TRAIT;
    }

    @Override
    public String component1() {
        return getShieldId();
    }

    @Override
    public String component2() {
        return getTrait();
    }

    @Override
    public String value1() {
        return getShieldId();
    }

    @Override
    public String value2() {
        return getTrait();
    }

    @Override
    public ShieldTraitRecord value1(String value) {
        setShieldId(value);
        return this;
    }

    @Override
    public ShieldTraitRecord value2(String value) {
        setTrait(value);
        return this;
    }

    @Override
    public ShieldTraitRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShieldTraitRecord
     */
    public ShieldTraitRecord() {
        super(ShieldTrait.SHIELD_TRAIT);
    }

    /**
     * Create a detached, initialised ShieldTraitRecord
     */
    public ShieldTraitRecord(String shieldId, String trait) {
        super(ShieldTrait.SHIELD_TRAIT);

        set(0, shieldId);
        set(1, trait);
    }
}
