/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.SkillActionKeySkill;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SkillActionKeySkillRecord extends UpdatableRecordImpl<SkillActionKeySkillRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 205913923;

    /**
     * Setter for <code>public.skill_action_key_skill.skill_action_id</code>.
     */
    public void setSkillActionId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.skill_action_key_skill.skill_action_id</code>.
     */
    public String getSkillActionId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.skill_action_key_skill.key_skill_id</code>.
     */
    public void setKeySkillId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.skill_action_key_skill.key_skill_id</code>.
     */
    public String getKeySkillId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SkillActionKeySkill.SKILL_ACTION_KEY_SKILL.SKILL_ACTION_ID;
    }

    @Override
    public Field<String> field2() {
        return SkillActionKeySkill.SKILL_ACTION_KEY_SKILL.KEY_SKILL_ID;
    }

    @Override
    public String component1() {
        return getSkillActionId();
    }

    @Override
    public String component2() {
        return getKeySkillId();
    }

    @Override
    public String value1() {
        return getSkillActionId();
    }

    @Override
    public String value2() {
        return getKeySkillId();
    }

    @Override
    public SkillActionKeySkillRecord value1(String value) {
        setSkillActionId(value);
        return this;
    }

    @Override
    public SkillActionKeySkillRecord value2(String value) {
        setKeySkillId(value);
        return this;
    }

    @Override
    public SkillActionKeySkillRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SkillActionKeySkillRecord
     */
    public SkillActionKeySkillRecord() {
        super(SkillActionKeySkill.SKILL_ACTION_KEY_SKILL);
    }

    /**
     * Create a detached, initialised SkillActionKeySkillRecord
     */
    public SkillActionKeySkillRecord(String skillActionId, String keySkillId) {
        super(SkillActionKeySkill.SKILL_ACTION_KEY_SKILL);

        set(0, skillActionId);
        set(1, keySkillId);
    }
}
