/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.SkillActionTrait;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SkillActionTraitRecord extends UpdatableRecordImpl<SkillActionTraitRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -2134049551;

    /**
     * Setter for <code>public.skill_action_trait.skill_action_id</code>.
     */
    public void setSkillActionId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.skill_action_trait.skill_action_id</code>.
     */
    public String getSkillActionId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.skill_action_trait.trait</code>.
     */
    public void setTrait(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.skill_action_trait.trait</code>.
     */
    public String getTrait() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SkillActionTrait.SKILL_ACTION_TRAIT.SKILL_ACTION_ID;
    }

    @Override
    public Field<String> field2() {
        return SkillActionTrait.SKILL_ACTION_TRAIT.TRAIT;
    }

    @Override
    public String component1() {
        return getSkillActionId();
    }

    @Override
    public String component2() {
        return getTrait();
    }

    @Override
    public String value1() {
        return getSkillActionId();
    }

    @Override
    public String value2() {
        return getTrait();
    }

    @Override
    public SkillActionTraitRecord value1(String value) {
        setSkillActionId(value);
        return this;
    }

    @Override
    public SkillActionTraitRecord value2(String value) {
        setTrait(value);
        return this;
    }

    @Override
    public SkillActionTraitRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SkillActionTraitRecord
     */
    public SkillActionTraitRecord() {
        super(SkillActionTrait.SKILL_ACTION_TRAIT);
    }

    /**
     * Create a detached, initialised SkillActionTraitRecord
     */
    public SkillActionTraitRecord(String skillActionId, String trait) {
        super(SkillActionTrait.SKILL_ACTION_TRAIT);

        set(0, skillActionId);
        set(1, trait);
    }
}
