/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.SpellTrait;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpellTraitRecord extends UpdatableRecordImpl<SpellTraitRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1169174360;

    /**
     * Setter for <code>public.spell_trait.spell_id</code>.
     */
    public void setSpellId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.spell_trait.spell_id</code>.
     */
    public String getSpellId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.spell_trait.trait</code>.
     */
    public void setTrait(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.spell_trait.trait</code>.
     */
    public String getTrait() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SpellTrait.SPELL_TRAIT.SPELL_ID;
    }

    @Override
    public Field<String> field2() {
        return SpellTrait.SPELL_TRAIT.TRAIT;
    }

    @Override
    public String component1() {
        return getSpellId();
    }

    @Override
    public String component2() {
        return getTrait();
    }

    @Override
    public String value1() {
        return getSpellId();
    }

    @Override
    public String value2() {
        return getTrait();
    }

    @Override
    public SpellTraitRecord value1(String value) {
        setSpellId(value);
        return this;
    }

    @Override
    public SpellTraitRecord value2(String value) {
        setTrait(value);
        return this;
    }

    @Override
    public SpellTraitRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpellTraitRecord
     */
    public SpellTraitRecord() {
        super(SpellTrait.SPELL_TRAIT);
    }

    /**
     * Create a detached, initialised SpellTraitRecord
     */
    public SpellTraitRecord(String spellId, String trait) {
        super(SpellTrait.SPELL_TRAIT);

        set(0, spellId);
        set(1, trait);
    }
}
