/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.SpellList;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpellListRecord extends UpdatableRecordImpl<SpellListRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 58985583;

    /**
     * Setter for <code>public.spell_list.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.spell_list.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.spell_list.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.spell_list.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SpellList.SPELL_LIST.ID;
    }

    @Override
    public Field<String> field2() {
        return SpellList.SPELL_LIST.NAME;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public SpellListRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SpellListRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SpellListRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpellListRecord
     */
    public SpellListRecord() {
        super(SpellList.SPELL_LIST);
    }

    /**
     * Create a detached, initialised SpellListRecord
     */
    public SpellListRecord(String id, String name) {
        super(SpellList.SPELL_LIST);

        set(0, id);
        set(1, name);
    }
}
