/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables.records;


import ai.ragu.charactermanager.jooq.tables.Weapon;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WeaponRecord extends UpdatableRecordImpl<WeaponRecord> implements Record15<String, String, String, Integer, Integer, String, Integer, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 2026338843;

    /**
     * Setter for <code>public.weapon.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.weapon.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.weapon.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.weapon.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.weapon.level</code>.
     */
    public void setLevel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.weapon.level</code>.
     */
    public String getLevel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.weapon.price</code>.
     */
    public void setPrice(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.weapon.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.weapon.weapon_proficiency</code>.
     */
    public void setWeaponProficiency(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.weapon.weapon_proficiency</code>.
     */
    public Integer getWeaponProficiency() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.weapon.ranged</code>.
     */
    public void setRanged(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.weapon.ranged</code>.
     */
    public String getRanged() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.weapon.damage</code>.
     */
    public void setDamage(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.weapon.damage</code>.
     */
    public Integer getDamage() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.weapon.damage_type</code>.
     */
    public void setDamageType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.weapon.damage_type</code>.
     */
    public String getDamageType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.weapon.range</code>.
     */
    public void setRange(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.weapon.range</code>.
     */
    public String getRange() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.weapon.reload</code>.
     */
    public void setReload(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.weapon.reload</code>.
     */
    public String getReload() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.weapon.bulk</code>.
     */
    public void setBulk(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.weapon.bulk</code>.
     */
    public String getBulk() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.weapon.hands</code>.
     */
    public void setHands(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.weapon.hands</code>.
     */
    public String getHands() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.weapon.group</code>.
     */
    public void setGroup(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.weapon.group</code>.
     */
    public String getGroup() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.weapon.src</code>.
     */
    public void setSrc(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.weapon.src</code>.
     */
    public String getSrc() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.weapon.url</code>.
     */
    public void setUrl(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.weapon.url</code>.
     */
    public String getUrl() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<String, String, String, Integer, Integer, String, Integer, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<String, String, String, Integer, Integer, String, Integer, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Weapon.WEAPON.ID;
    }

    @Override
    public Field<String> field2() {
        return Weapon.WEAPON.NAME;
    }

    @Override
    public Field<String> field3() {
        return Weapon.WEAPON.LEVEL;
    }

    @Override
    public Field<Integer> field4() {
        return Weapon.WEAPON.PRICE;
    }

    @Override
    public Field<Integer> field5() {
        return Weapon.WEAPON.WEAPON_PROFICIENCY;
    }

    @Override
    public Field<String> field6() {
        return Weapon.WEAPON.RANGED;
    }

    @Override
    public Field<Integer> field7() {
        return Weapon.WEAPON.DAMAGE;
    }

    @Override
    public Field<String> field8() {
        return Weapon.WEAPON.DAMAGE_TYPE;
    }

    @Override
    public Field<String> field9() {
        return Weapon.WEAPON.RANGE;
    }

    @Override
    public Field<String> field10() {
        return Weapon.WEAPON.RELOAD;
    }

    @Override
    public Field<String> field11() {
        return Weapon.WEAPON.BULK;
    }

    @Override
    public Field<String> field12() {
        return Weapon.WEAPON.HANDS;
    }

    @Override
    public Field<String> field13() {
        return Weapon.WEAPON.GROUP;
    }

    @Override
    public Field<String> field14() {
        return Weapon.WEAPON.SRC;
    }

    @Override
    public Field<String> field15() {
        return Weapon.WEAPON.URL;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getLevel();
    }

    @Override
    public Integer component4() {
        return getPrice();
    }

    @Override
    public Integer component5() {
        return getWeaponProficiency();
    }

    @Override
    public String component6() {
        return getRanged();
    }

    @Override
    public Integer component7() {
        return getDamage();
    }

    @Override
    public String component8() {
        return getDamageType();
    }

    @Override
    public String component9() {
        return getRange();
    }

    @Override
    public String component10() {
        return getReload();
    }

    @Override
    public String component11() {
        return getBulk();
    }

    @Override
    public String component12() {
        return getHands();
    }

    @Override
    public String component13() {
        return getGroup();
    }

    @Override
    public String component14() {
        return getSrc();
    }

    @Override
    public String component15() {
        return getUrl();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getLevel();
    }

    @Override
    public Integer value4() {
        return getPrice();
    }

    @Override
    public Integer value5() {
        return getWeaponProficiency();
    }

    @Override
    public String value6() {
        return getRanged();
    }

    @Override
    public Integer value7() {
        return getDamage();
    }

    @Override
    public String value8() {
        return getDamageType();
    }

    @Override
    public String value9() {
        return getRange();
    }

    @Override
    public String value10() {
        return getReload();
    }

    @Override
    public String value11() {
        return getBulk();
    }

    @Override
    public String value12() {
        return getHands();
    }

    @Override
    public String value13() {
        return getGroup();
    }

    @Override
    public String value14() {
        return getSrc();
    }

    @Override
    public String value15() {
        return getUrl();
    }

    @Override
    public WeaponRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public WeaponRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public WeaponRecord value3(String value) {
        setLevel(value);
        return this;
    }

    @Override
    public WeaponRecord value4(Integer value) {
        setPrice(value);
        return this;
    }

    @Override
    public WeaponRecord value5(Integer value) {
        setWeaponProficiency(value);
        return this;
    }

    @Override
    public WeaponRecord value6(String value) {
        setRanged(value);
        return this;
    }

    @Override
    public WeaponRecord value7(Integer value) {
        setDamage(value);
        return this;
    }

    @Override
    public WeaponRecord value8(String value) {
        setDamageType(value);
        return this;
    }

    @Override
    public WeaponRecord value9(String value) {
        setRange(value);
        return this;
    }

    @Override
    public WeaponRecord value10(String value) {
        setReload(value);
        return this;
    }

    @Override
    public WeaponRecord value11(String value) {
        setBulk(value);
        return this;
    }

    @Override
    public WeaponRecord value12(String value) {
        setHands(value);
        return this;
    }

    @Override
    public WeaponRecord value13(String value) {
        setGroup(value);
        return this;
    }

    @Override
    public WeaponRecord value14(String value) {
        setSrc(value);
        return this;
    }

    @Override
    public WeaponRecord value15(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public WeaponRecord values(String value1, String value2, String value3, Integer value4, Integer value5, String value6, Integer value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WeaponRecord
     */
    public WeaponRecord() {
        super(Weapon.WEAPON);
    }

    /**
     * Create a detached, initialised WeaponRecord
     */
    public WeaponRecord(String id, String name, String level, Integer price, Integer weaponProficiency, String ranged, Integer damage, String damageType, String range, String reload, String bulk, String hands, String group, String src, String url) {
        super(Weapon.WEAPON);

        set(0, id);
        set(1, name);
        set(2, level);
        set(3, price);
        set(4, weaponProficiency);
        set(5, ranged);
        set(6, damage);
        set(7, damageType);
        set(8, range);
        set(9, reload);
        set(10, bulk);
        set(11, hands);
        set(12, group);
        set(13, src);
        set(14, url);
    }
}
