/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables;


import ai.ragu.charactermanager.jooq.Keys;
import ai.ragu.charactermanager.jooq.Public;
import ai.ragu.charactermanager.jooq.tables.records.AncestryAbilityFlawsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AncestryAbilityFlaws extends TableImpl<AncestryAbilityFlawsRecord> {

    private static final long serialVersionUID = 2064613492;

    /**
     * The reference instance of <code>public.ancestry_ability_flaws</code>
     */
    public static final AncestryAbilityFlaws ANCESTRY_ABILITY_FLAWS = new AncestryAbilityFlaws();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AncestryAbilityFlawsRecord> getRecordType() {
        return AncestryAbilityFlawsRecord.class;
    }

    /**
     * The column <code>public.ancestry_ability_flaws.ancestry_id</code>.
     */
    public final TableField<AncestryAbilityFlawsRecord, String> ANCESTRY_ID = createField(DSL.name("ancestry_id"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.ancestry_ability_flaws.ability_score_id</code>.
     */
    public final TableField<AncestryAbilityFlawsRecord, String> ABILITY_SCORE_ID = createField(DSL.name("ability_score_id"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * Create a <code>public.ancestry_ability_flaws</code> table reference
     */
    public AncestryAbilityFlaws() {
        this(DSL.name("ancestry_ability_flaws"), null);
    }

    /**
     * Create an aliased <code>public.ancestry_ability_flaws</code> table reference
     */
    public AncestryAbilityFlaws(String alias) {
        this(DSL.name(alias), ANCESTRY_ABILITY_FLAWS);
    }

    /**
     * Create an aliased <code>public.ancestry_ability_flaws</code> table reference
     */
    public AncestryAbilityFlaws(Name alias) {
        this(alias, ANCESTRY_ABILITY_FLAWS);
    }

    private AncestryAbilityFlaws(Name alias, Table<AncestryAbilityFlawsRecord> aliased) {
        this(alias, aliased, null);
    }

    private AncestryAbilityFlaws(Name alias, Table<AncestryAbilityFlawsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> AncestryAbilityFlaws(Table<O> child, ForeignKey<O, AncestryAbilityFlawsRecord> key) {
        super(child, key, ANCESTRY_ABILITY_FLAWS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<AncestryAbilityFlawsRecord> getPrimaryKey() {
        return Keys.ANCESTRY_ABILITY_FLAWS_PKEY;
    }

    @Override
    public List<UniqueKey<AncestryAbilityFlawsRecord>> getKeys() {
        return Arrays.<UniqueKey<AncestryAbilityFlawsRecord>>asList(Keys.ANCESTRY_ABILITY_FLAWS_PKEY);
    }

    @Override
    public List<ForeignKey<AncestryAbilityFlawsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AncestryAbilityFlawsRecord, ?>>asList(Keys.ANCESTRY_ABILITY_FLAWS__ANCESTRY_ABILITY_FLAWS_ANCESTRY_ID_FKEY, Keys.ANCESTRY_ABILITY_FLAWS__ANCESTRY_ABILITY_FLAWS_ABILITY_SCORE_ID_FKEY);
    }

    public Ancestry ancestry() {
        return new Ancestry(this, Keys.ANCESTRY_ABILITY_FLAWS__ANCESTRY_ABILITY_FLAWS_ANCESTRY_ID_FKEY);
    }

    public AbilityScore abilityScore() {
        return new AbilityScore(this, Keys.ANCESTRY_ABILITY_FLAWS__ANCESTRY_ABILITY_FLAWS_ABILITY_SCORE_ID_FKEY);
    }

    @Override
    public AncestryAbilityFlaws as(String alias) {
        return new AncestryAbilityFlaws(DSL.name(alias), this);
    }

    @Override
    public AncestryAbilityFlaws as(Name alias) {
        return new AncestryAbilityFlaws(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AncestryAbilityFlaws rename(String name) {
        return new AncestryAbilityFlaws(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AncestryAbilityFlaws rename(Name name) {
        return new AncestryAbilityFlaws(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
