/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables;


import ai.ragu.charactermanager.jooq.Keys;
import ai.ragu.charactermanager.jooq.Public;
import ai.ragu.charactermanager.jooq.tables.records.AncestryTraitRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AncestryTrait extends TableImpl<AncestryTraitRecord> {

    private static final long serialVersionUID = 786431050;

    /**
     * The reference instance of <code>public.ancestry_trait</code>
     */
    public static final AncestryTrait ANCESTRY_TRAIT = new AncestryTrait();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AncestryTraitRecord> getRecordType() {
        return AncestryTraitRecord.class;
    }

    /**
     * The column <code>public.ancestry_trait.ancestry_id</code>.
     */
    public final TableField<AncestryTraitRecord, String> ANCESTRY_ID = createField(DSL.name("ancestry_id"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.ancestry_trait.trait</code>.
     */
    public final TableField<AncestryTraitRecord, String> TRAIT = createField(DSL.name("trait"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * Create a <code>public.ancestry_trait</code> table reference
     */
    public AncestryTrait() {
        this(DSL.name("ancestry_trait"), null);
    }

    /**
     * Create an aliased <code>public.ancestry_trait</code> table reference
     */
    public AncestryTrait(String alias) {
        this(DSL.name(alias), ANCESTRY_TRAIT);
    }

    /**
     * Create an aliased <code>public.ancestry_trait</code> table reference
     */
    public AncestryTrait(Name alias) {
        this(alias, ANCESTRY_TRAIT);
    }

    private AncestryTrait(Name alias, Table<AncestryTraitRecord> aliased) {
        this(alias, aliased, null);
    }

    private AncestryTrait(Name alias, Table<AncestryTraitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> AncestryTrait(Table<O> child, ForeignKey<O, AncestryTraitRecord> key) {
        super(child, key, ANCESTRY_TRAIT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<AncestryTraitRecord> getPrimaryKey() {
        return Keys.ANCESTRY_TRAIT_PKEY;
    }

    @Override
    public List<UniqueKey<AncestryTraitRecord>> getKeys() {
        return Arrays.<UniqueKey<AncestryTraitRecord>>asList(Keys.ANCESTRY_TRAIT_PKEY);
    }

    @Override
    public List<ForeignKey<AncestryTraitRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AncestryTraitRecord, ?>>asList(Keys.ANCESTRY_TRAIT__ANCESTRY_TRAIT_ANCESTRY_ID_FKEY);
    }

    public Ancestry ancestry() {
        return new Ancestry(this, Keys.ANCESTRY_TRAIT__ANCESTRY_TRAIT_ANCESTRY_ID_FKEY);
    }

    @Override
    public AncestryTrait as(String alias) {
        return new AncestryTrait(DSL.name(alias), this);
    }

    @Override
    public AncestryTrait as(Name alias) {
        return new AncestryTrait(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AncestryTrait rename(String name) {
        return new AncestryTrait(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AncestryTrait rename(Name name) {
        return new AncestryTrait(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
