/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables;


import ai.ragu.charactermanager.jooq.Keys;
import ai.ragu.charactermanager.jooq.Public;
import ai.ragu.charactermanager.jooq.tables.records.FeatSkillRequirementRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeatSkillRequirement extends TableImpl<FeatSkillRequirementRecord> {

    private static final long serialVersionUID = 1806589967;

    /**
     * The reference instance of <code>public.feat_skill_requirement</code>
     */
    public static final FeatSkillRequirement FEAT_SKILL_REQUIREMENT = new FeatSkillRequirement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FeatSkillRequirementRecord> getRecordType() {
        return FeatSkillRequirementRecord.class;
    }

    /**
     * The column <code>public.feat_skill_requirement.feat_id</code>.
     */
    public final TableField<FeatSkillRequirementRecord, String> FEAT_ID = createField(DSL.name("feat_id"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.feat_skill_requirement.skill_id</code>.
     */
    public final TableField<FeatSkillRequirementRecord, String> SKILL_ID = createField(DSL.name("skill_id"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.feat_skill_requirement.training_level_id</code>.
     */
    public final TableField<FeatSkillRequirementRecord, String> TRAINING_LEVEL_ID = createField(DSL.name("training_level_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.feat_skill_requirement</code> table reference
     */
    public FeatSkillRequirement() {
        this(DSL.name("feat_skill_requirement"), null);
    }

    /**
     * Create an aliased <code>public.feat_skill_requirement</code> table reference
     */
    public FeatSkillRequirement(String alias) {
        this(DSL.name(alias), FEAT_SKILL_REQUIREMENT);
    }

    /**
     * Create an aliased <code>public.feat_skill_requirement</code> table reference
     */
    public FeatSkillRequirement(Name alias) {
        this(alias, FEAT_SKILL_REQUIREMENT);
    }

    private FeatSkillRequirement(Name alias, Table<FeatSkillRequirementRecord> aliased) {
        this(alias, aliased, null);
    }

    private FeatSkillRequirement(Name alias, Table<FeatSkillRequirementRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> FeatSkillRequirement(Table<O> child, ForeignKey<O, FeatSkillRequirementRecord> key) {
        super(child, key, FEAT_SKILL_REQUIREMENT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<FeatSkillRequirementRecord> getPrimaryKey() {
        return Keys.FEAT_SKILL_REQUIREMENT_PKEY;
    }

    @Override
    public List<UniqueKey<FeatSkillRequirementRecord>> getKeys() {
        return Arrays.<UniqueKey<FeatSkillRequirementRecord>>asList(Keys.FEAT_SKILL_REQUIREMENT_PKEY);
    }

    @Override
    public List<ForeignKey<FeatSkillRequirementRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<FeatSkillRequirementRecord, ?>>asList(Keys.FEAT_SKILL_REQUIREMENT__FEAT_SKILL_REQUIREMENT_FEAT_ID_FKEY, Keys.FEAT_SKILL_REQUIREMENT__FEAT_SKILL_REQUIREMENT_SKILL_ID_FKEY, Keys.FEAT_SKILL_REQUIREMENT__FEAT_SKILL_REQUIREMENT_TRAINING_LEVEL_ID_FKEY);
    }

    public Feat feat() {
        return new Feat(this, Keys.FEAT_SKILL_REQUIREMENT__FEAT_SKILL_REQUIREMENT_FEAT_ID_FKEY);
    }

    public Skill skill() {
        return new Skill(this, Keys.FEAT_SKILL_REQUIREMENT__FEAT_SKILL_REQUIREMENT_SKILL_ID_FKEY);
    }

    public TrainingLevel trainingLevel() {
        return new TrainingLevel(this, Keys.FEAT_SKILL_REQUIREMENT__FEAT_SKILL_REQUIREMENT_TRAINING_LEVEL_ID_FKEY);
    }

    @Override
    public FeatSkillRequirement as(String alias) {
        return new FeatSkillRequirement(DSL.name(alias), this);
    }

    @Override
    public FeatSkillRequirement as(Name alias) {
        return new FeatSkillRequirement(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FeatSkillRequirement rename(String name) {
        return new FeatSkillRequirement(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeatSkillRequirement rename(Name name) {
        return new FeatSkillRequirement(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
