/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables;


import ai.ragu.charactermanager.jooq.Keys;
import ai.ragu.charactermanager.jooq.Public;
import ai.ragu.charactermanager.jooq.tables.records.MagicWeaponTraitRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MagicWeaponTrait extends TableImpl<MagicWeaponTraitRecord> {

    private static final long serialVersionUID = -2023594070;

    /**
     * The reference instance of <code>public.magic_weapon_trait</code>
     */
    public static final MagicWeaponTrait MAGIC_WEAPON_TRAIT = new MagicWeaponTrait();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MagicWeaponTraitRecord> getRecordType() {
        return MagicWeaponTraitRecord.class;
    }

    /**
     * The column <code>public.magic_weapon_trait.magic_weapon_id</code>.
     */
    public final TableField<MagicWeaponTraitRecord, String> MAGIC_WEAPON_ID = createField(DSL.name("magic_weapon_id"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.magic_weapon_trait.trait</code>.
     */
    public final TableField<MagicWeaponTraitRecord, String> TRAIT = createField(DSL.name("trait"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * Create a <code>public.magic_weapon_trait</code> table reference
     */
    public MagicWeaponTrait() {
        this(DSL.name("magic_weapon_trait"), null);
    }

    /**
     * Create an aliased <code>public.magic_weapon_trait</code> table reference
     */
    public MagicWeaponTrait(String alias) {
        this(DSL.name(alias), MAGIC_WEAPON_TRAIT);
    }

    /**
     * Create an aliased <code>public.magic_weapon_trait</code> table reference
     */
    public MagicWeaponTrait(Name alias) {
        this(alias, MAGIC_WEAPON_TRAIT);
    }

    private MagicWeaponTrait(Name alias, Table<MagicWeaponTraitRecord> aliased) {
        this(alias, aliased, null);
    }

    private MagicWeaponTrait(Name alias, Table<MagicWeaponTraitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> MagicWeaponTrait(Table<O> child, ForeignKey<O, MagicWeaponTraitRecord> key) {
        super(child, key, MAGIC_WEAPON_TRAIT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<MagicWeaponTraitRecord> getPrimaryKey() {
        return Keys.MAGIC_WEAPON_TRAIT_PKEY;
    }

    @Override
    public List<UniqueKey<MagicWeaponTraitRecord>> getKeys() {
        return Arrays.<UniqueKey<MagicWeaponTraitRecord>>asList(Keys.MAGIC_WEAPON_TRAIT_PKEY);
    }

    @Override
    public List<ForeignKey<MagicWeaponTraitRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MagicWeaponTraitRecord, ?>>asList(Keys.MAGIC_WEAPON_TRAIT__MAGIC_WEAPON_TRAIT_MAGIC_WEAPON_ID_FKEY);
    }

    public MagicWeapon magicWeapon() {
        return new MagicWeapon(this, Keys.MAGIC_WEAPON_TRAIT__MAGIC_WEAPON_TRAIT_MAGIC_WEAPON_ID_FKEY);
    }

    @Override
    public MagicWeaponTrait as(String alias) {
        return new MagicWeaponTrait(DSL.name(alias), this);
    }

    @Override
    public MagicWeaponTrait as(Name alias) {
        return new MagicWeaponTrait(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MagicWeaponTrait rename(String name) {
        return new MagicWeaponTrait(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MagicWeaponTrait rename(Name name) {
        return new MagicWeaponTrait(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
