/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables;


import ai.ragu.charactermanager.jooq.Keys;
import ai.ragu.charactermanager.jooq.Public;
import ai.ragu.charactermanager.jooq.tables.records.MagicArmorTraitRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MagicArmorTrait extends TableImpl<MagicArmorTraitRecord> {

    private static final long serialVersionUID = -821868074;

    /**
     * The reference instance of <code>public.magic_armor_trait</code>
     */
    public static final MagicArmorTrait MAGIC_ARMOR_TRAIT = new MagicArmorTrait();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MagicArmorTraitRecord> getRecordType() {
        return MagicArmorTraitRecord.class;
    }

    /**
     * The column <code>public.magic_armor_trait.magic_armor_id</code>.
     */
    public final TableField<MagicArmorTraitRecord, String> MAGIC_ARMOR_ID = createField(DSL.name("magic_armor_id"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.magic_armor_trait.trait</code>.
     */
    public final TableField<MagicArmorTraitRecord, String> TRAIT = createField(DSL.name("trait"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * Create a <code>public.magic_armor_trait</code> table reference
     */
    public MagicArmorTrait() {
        this(DSL.name("magic_armor_trait"), null);
    }

    /**
     * Create an aliased <code>public.magic_armor_trait</code> table reference
     */
    public MagicArmorTrait(String alias) {
        this(DSL.name(alias), MAGIC_ARMOR_TRAIT);
    }

    /**
     * Create an aliased <code>public.magic_armor_trait</code> table reference
     */
    public MagicArmorTrait(Name alias) {
        this(alias, MAGIC_ARMOR_TRAIT);
    }

    private MagicArmorTrait(Name alias, Table<MagicArmorTraitRecord> aliased) {
        this(alias, aliased, null);
    }

    private MagicArmorTrait(Name alias, Table<MagicArmorTraitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> MagicArmorTrait(Table<O> child, ForeignKey<O, MagicArmorTraitRecord> key) {
        super(child, key, MAGIC_ARMOR_TRAIT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<MagicArmorTraitRecord> getPrimaryKey() {
        return Keys.MAGIC_ARMOR_TRAIT_PKEY;
    }

    @Override
    public List<UniqueKey<MagicArmorTraitRecord>> getKeys() {
        return Arrays.<UniqueKey<MagicArmorTraitRecord>>asList(Keys.MAGIC_ARMOR_TRAIT_PKEY);
    }

    @Override
    public List<ForeignKey<MagicArmorTraitRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MagicArmorTraitRecord, ?>>asList(Keys.MAGIC_ARMOR_TRAIT__MAGIC_ARMOR_TRAIT_MAGIC_ARMOR_ID_FKEY);
    }

    public MagicArmor magicArmor() {
        return new MagicArmor(this, Keys.MAGIC_ARMOR_TRAIT__MAGIC_ARMOR_TRAIT_MAGIC_ARMOR_ID_FKEY);
    }

    @Override
    public MagicArmorTrait as(String alias) {
        return new MagicArmorTrait(DSL.name(alias), this);
    }

    @Override
    public MagicArmorTrait as(Name alias) {
        return new MagicArmorTrait(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MagicArmorTrait rename(String name) {
        return new MagicArmorTrait(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MagicArmorTrait rename(Name name) {
        return new MagicArmorTrait(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
