/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables;


import ai.ragu.charactermanager.jooq.Keys;
import ai.ragu.charactermanager.jooq.Public;
import ai.ragu.charactermanager.jooq.tables.records.SpecialTraitRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpecialTrait extends TableImpl<SpecialTraitRecord> {

    private static final long serialVersionUID = -2003888332;

    /**
     * The reference instance of <code>public.special_trait</code>
     */
    public static final SpecialTrait SPECIAL_TRAIT = new SpecialTrait();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpecialTraitRecord> getRecordType() {
        return SpecialTraitRecord.class;
    }

    /**
     * The column <code>public.special_trait.special_id</code>.
     */
    public final TableField<SpecialTraitRecord, String> SPECIAL_ID = createField(DSL.name("special_id"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.special_trait.trait</code>.
     */
    public final TableField<SpecialTraitRecord, String> TRAIT = createField(DSL.name("trait"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * Create a <code>public.special_trait</code> table reference
     */
    public SpecialTrait() {
        this(DSL.name("special_trait"), null);
    }

    /**
     * Create an aliased <code>public.special_trait</code> table reference
     */
    public SpecialTrait(String alias) {
        this(DSL.name(alias), SPECIAL_TRAIT);
    }

    /**
     * Create an aliased <code>public.special_trait</code> table reference
     */
    public SpecialTrait(Name alias) {
        this(alias, SPECIAL_TRAIT);
    }

    private SpecialTrait(Name alias, Table<SpecialTraitRecord> aliased) {
        this(alias, aliased, null);
    }

    private SpecialTrait(Name alias, Table<SpecialTraitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> SpecialTrait(Table<O> child, ForeignKey<O, SpecialTraitRecord> key) {
        super(child, key, SPECIAL_TRAIT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<SpecialTraitRecord> getPrimaryKey() {
        return Keys.SPECIAL_TRAIT_PKEY;
    }

    @Override
    public List<UniqueKey<SpecialTraitRecord>> getKeys() {
        return Arrays.<UniqueKey<SpecialTraitRecord>>asList(Keys.SPECIAL_TRAIT_PKEY);
    }

    @Override
    public List<ForeignKey<SpecialTraitRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SpecialTraitRecord, ?>>asList(Keys.SPECIAL_TRAIT__SPECIAL_TRAIT_SPECIAL_ID_FKEY);
    }

    public Special special() {
        return new Special(this, Keys.SPECIAL_TRAIT__SPECIAL_TRAIT_SPECIAL_ID_FKEY);
    }

    @Override
    public SpecialTrait as(String alias) {
        return new SpecialTrait(DSL.name(alias), this);
    }

    @Override
    public SpecialTrait as(Name alias) {
        return new SpecialTrait(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpecialTrait rename(String name) {
        return new SpecialTrait(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpecialTrait rename(Name name) {
        return new SpecialTrait(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
