/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables;


import ai.ragu.charactermanager.jooq.Keys;
import ai.ragu.charactermanager.jooq.Public;
import ai.ragu.charactermanager.jooq.tables.records.SpellListRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpellList extends TableImpl<SpellListRecord> {

    private static final long serialVersionUID = -1200221365;

    /**
     * The reference instance of <code>public.spell_list</code>
     */
    public static final SpellList SPELL_LIST = new SpellList();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpellListRecord> getRecordType() {
        return SpellListRecord.class;
    }

    /**
     * The column <code>public.spell_list.id</code>.
     */
    public final TableField<SpellListRecord, String> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.spell_list.name</code>.
     */
    public final TableField<SpellListRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.spell_list</code> table reference
     */
    public SpellList() {
        this(DSL.name("spell_list"), null);
    }

    /**
     * Create an aliased <code>public.spell_list</code> table reference
     */
    public SpellList(String alias) {
        this(DSL.name(alias), SPELL_LIST);
    }

    /**
     * Create an aliased <code>public.spell_list</code> table reference
     */
    public SpellList(Name alias) {
        this(alias, SPELL_LIST);
    }

    private SpellList(Name alias, Table<SpellListRecord> aliased) {
        this(alias, aliased, null);
    }

    private SpellList(Name alias, Table<SpellListRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> SpellList(Table<O> child, ForeignKey<O, SpellListRecord> key) {
        super(child, key, SPELL_LIST);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<SpellListRecord> getPrimaryKey() {
        return Keys.SPELL_LIST_PKEY;
    }

    @Override
    public List<UniqueKey<SpellListRecord>> getKeys() {
        return Arrays.<UniqueKey<SpellListRecord>>asList(Keys.SPELL_LIST_PKEY);
    }

    @Override
    public SpellList as(String alias) {
        return new SpellList(DSL.name(alias), this);
    }

    @Override
    public SpellList as(Name alias) {
        return new SpellList(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpellList rename(String name) {
        return new SpellList(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpellList rename(Name name) {
        return new SpellList(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
