/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables;


import ai.ragu.charactermanager.jooq.Keys;
import ai.ragu.charactermanager.jooq.Public;
import ai.ragu.charactermanager.jooq.tables.records.SpellsBloodlineRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row22;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpellsBloodline extends TableImpl<SpellsBloodlineRecord> {

    private static final long serialVersionUID = -582233256;

    /**
     * The reference instance of <code>public.spells_bloodline</code>
     */
    public static final SpellsBloodline SPELLS_BLOODLINE = new SpellsBloodline();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpellsBloodlineRecord> getRecordType() {
        return SpellsBloodlineRecord.class;
    }

    /**
     * The column <code>public.spells_bloodline.id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.spells_bloodline.name</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.spell_list_id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> SPELL_LIST_ID = createField(DSL.name("spell_list_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.skill1_id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> SKILL1_ID = createField(DSL.name("skill1_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.skill2_id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> SKILL2_ID = createField(DSL.name("skill2_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.granted_cantrip_id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> GRANTED_CANTRIP_ID = createField(DSL.name("granted_cantrip_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.granted_1st_level_spell_id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> GRANTED_1ST_LEVEL_SPELL_ID = createField(DSL.name("granted_1st_level_spell_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.granted_2nd_level_spell_id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> GRANTED_2ND_LEVEL_SPELL_ID = createField(DSL.name("granted_2nd_level_spell_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.granted_3rd_level_spell_id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> GRANTED_3RD_LEVEL_SPELL_ID = createField(DSL.name("granted_3rd_level_spell_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.granted_4th_level_spell_id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> GRANTED_4TH_LEVEL_SPELL_ID = createField(DSL.name("granted_4th_level_spell_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.granted_5th_level_spell_id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> GRANTED_5TH_LEVEL_SPELL_ID = createField(DSL.name("granted_5th_level_spell_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.granted_6th_level_spell_id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> GRANTED_6TH_LEVEL_SPELL_ID = createField(DSL.name("granted_6th_level_spell_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.granted_7th_level_spell_id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> GRANTED_7TH_LEVEL_SPELL_ID = createField(DSL.name("granted_7th_level_spell_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.granted_8th_level_spell_id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> GRANTED_8TH_LEVEL_SPELL_ID = createField(DSL.name("granted_8th_level_spell_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.granted_9th_level_spell_id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> GRANTED_9TH_LEVEL_SPELL_ID = createField(DSL.name("granted_9th_level_spell_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.initial_spell_id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> INITIAL_SPELL_ID = createField(DSL.name("initial_spell_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.advanced_spell_id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> ADVANCED_SPELL_ID = createField(DSL.name("advanced_spell_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.greater_spell_id</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> GREATER_SPELL_ID = createField(DSL.name("greater_spell_id"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.blood_magic</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> BLOOD_MAGIC = createField(DSL.name("blood_magic"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.description</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> DESCRIPTION = createField(DSL.name("description"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.src</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> SRC = createField(DSL.name("src"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.spells_bloodline.url</code>.
     */
    public final TableField<SpellsBloodlineRecord, String> URL = createField(DSL.name("url"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.spells_bloodline</code> table reference
     */
    public SpellsBloodline() {
        this(DSL.name("spells_bloodline"), null);
    }

    /**
     * Create an aliased <code>public.spells_bloodline</code> table reference
     */
    public SpellsBloodline(String alias) {
        this(DSL.name(alias), SPELLS_BLOODLINE);
    }

    /**
     * Create an aliased <code>public.spells_bloodline</code> table reference
     */
    public SpellsBloodline(Name alias) {
        this(alias, SPELLS_BLOODLINE);
    }

    private SpellsBloodline(Name alias, Table<SpellsBloodlineRecord> aliased) {
        this(alias, aliased, null);
    }

    private SpellsBloodline(Name alias, Table<SpellsBloodlineRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> SpellsBloodline(Table<O> child, ForeignKey<O, SpellsBloodlineRecord> key) {
        super(child, key, SPELLS_BLOODLINE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<SpellsBloodlineRecord> getPrimaryKey() {
        return Keys.SPELLS_BLOODLINE_PKEY;
    }

    @Override
    public List<UniqueKey<SpellsBloodlineRecord>> getKeys() {
        return Arrays.<UniqueKey<SpellsBloodlineRecord>>asList(Keys.SPELLS_BLOODLINE_PKEY);
    }

    @Override
    public List<ForeignKey<SpellsBloodlineRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SpellsBloodlineRecord, ?>>asList(Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_SPELL_LIST_ID_FKEY, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_SKILL1_ID_FKEY, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_SKILL2_ID_FKEY, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_CANTRIP_ID_FKEY, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_1ST_LEVEL_SPELL_ID_FKEY, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_2ND_LEVEL_SPELL_ID_FKEY, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_3RD_LEVEL_SPELL_ID_FKEY, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_4TH_LEVEL_SPELL_ID_FKEY, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_5TH_LEVEL_SPELL_ID_FKEY, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_6TH_LEVEL_SPELL_ID_FKEY, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_7TH_LEVEL_SPELL_ID_FKEY, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_8TH_LEVEL_SPELL_ID_FKEY, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_9TH_LEVEL_SPELL_ID_FKEY, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_INITIAL_SPELL_ID_FKEY, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_ADVANCED_SPELL_ID_FKEY, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GREATER_SPELL_ID_FKEY, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_SRC_FKEY);
    }

    public SpellList spellList() {
        return new SpellList(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_SPELL_LIST_ID_FKEY);
    }

    public Skill spellsBloodlineSkill1IdFkey() {
        return new Skill(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_SKILL1_ID_FKEY);
    }

    public Skill spellsBloodlineSkill2IdFkey() {
        return new Skill(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_SKILL2_ID_FKEY);
    }

    public Spell spellsBloodlineGrantedCantripIdFkey() {
        return new Spell(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_CANTRIP_ID_FKEY);
    }

    public Spell spellsBloodlineGranted_1stLevelSpellIdFkey() {
        return new Spell(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_1ST_LEVEL_SPELL_ID_FKEY);
    }

    public Spell spellsBloodlineGranted_2ndLevelSpellIdFkey() {
        return new Spell(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_2ND_LEVEL_SPELL_ID_FKEY);
    }

    public Spell spellsBloodlineGranted_3rdLevelSpellIdFkey() {
        return new Spell(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_3RD_LEVEL_SPELL_ID_FKEY);
    }

    public Spell spellsBloodlineGranted_4thLevelSpellIdFkey() {
        return new Spell(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_4TH_LEVEL_SPELL_ID_FKEY);
    }

    public Spell spellsBloodlineGranted_5thLevelSpellIdFkey() {
        return new Spell(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_5TH_LEVEL_SPELL_ID_FKEY);
    }

    public Spell spellsBloodlineGranted_6thLevelSpellIdFkey() {
        return new Spell(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_6TH_LEVEL_SPELL_ID_FKEY);
    }

    public Spell spellsBloodlineGranted_7thLevelSpellIdFkey() {
        return new Spell(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_7TH_LEVEL_SPELL_ID_FKEY);
    }

    public Spell spellsBloodlineGranted_8thLevelSpellIdFkey() {
        return new Spell(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_8TH_LEVEL_SPELL_ID_FKEY);
    }

    public Spell spellsBloodlineGranted_9thLevelSpellIdFkey() {
        return new Spell(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GRANTED_9TH_LEVEL_SPELL_ID_FKEY);
    }

    public Spell spellsBloodlineInitialSpellIdFkey() {
        return new Spell(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_INITIAL_SPELL_ID_FKEY);
    }

    public Spell spellsBloodlineAdvancedSpellIdFkey() {
        return new Spell(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_ADVANCED_SPELL_ID_FKEY);
    }

    public Spell spellsBloodlineGreaterSpellIdFkey() {
        return new Spell(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_GREATER_SPELL_ID_FKEY);
    }

    public RulesSource rulesSource() {
        return new RulesSource(this, Keys.SPELLS_BLOODLINE__SPELLS_BLOODLINE_SRC_FKEY);
    }

    @Override
    public SpellsBloodline as(String alias) {
        return new SpellsBloodline(DSL.name(alias), this);
    }

    @Override
    public SpellsBloodline as(Name alias) {
        return new SpellsBloodline(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpellsBloodline rename(String name) {
        return new SpellsBloodline(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpellsBloodline rename(Name name) {
        return new SpellsBloodline(name, null);
    }

    // -------------------------------------------------------------------------
    // Row22 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row22<String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row22) super.fieldsRow();
    }
}
