/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables;


import ai.ragu.charactermanager.jooq.Keys;
import ai.ragu.charactermanager.jooq.Public;
import ai.ragu.charactermanager.jooq.tables.records.SpellTraitRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpellTrait extends TableImpl<SpellTraitRecord> {

    private static final long serialVersionUID = 1147889198;

    /**
     * The reference instance of <code>public.spell_trait</code>
     */
    public static final SpellTrait SPELL_TRAIT = new SpellTrait();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpellTraitRecord> getRecordType() {
        return SpellTraitRecord.class;
    }

    /**
     * The column <code>public.spell_trait.spell_id</code>.
     */
    public final TableField<SpellTraitRecord, String> SPELL_ID = createField(DSL.name("spell_id"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.spell_trait.trait</code>.
     */
    public final TableField<SpellTraitRecord, String> TRAIT = createField(DSL.name("trait"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * Create a <code>public.spell_trait</code> table reference
     */
    public SpellTrait() {
        this(DSL.name("spell_trait"), null);
    }

    /**
     * Create an aliased <code>public.spell_trait</code> table reference
     */
    public SpellTrait(String alias) {
        this(DSL.name(alias), SPELL_TRAIT);
    }

    /**
     * Create an aliased <code>public.spell_trait</code> table reference
     */
    public SpellTrait(Name alias) {
        this(alias, SPELL_TRAIT);
    }

    private SpellTrait(Name alias, Table<SpellTraitRecord> aliased) {
        this(alias, aliased, null);
    }

    private SpellTrait(Name alias, Table<SpellTraitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> SpellTrait(Table<O> child, ForeignKey<O, SpellTraitRecord> key) {
        super(child, key, SPELL_TRAIT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<SpellTraitRecord> getPrimaryKey() {
        return Keys.SPELL_TRAIT_PKEY;
    }

    @Override
    public List<UniqueKey<SpellTraitRecord>> getKeys() {
        return Arrays.<UniqueKey<SpellTraitRecord>>asList(Keys.SPELL_TRAIT_PKEY);
    }

    @Override
    public List<ForeignKey<SpellTraitRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SpellTraitRecord, ?>>asList(Keys.SPELL_TRAIT__SPELL_TRAIT_SPELL_ID_FKEY);
    }

    public Spell spell() {
        return new Spell(this, Keys.SPELL_TRAIT__SPELL_TRAIT_SPELL_ID_FKEY);
    }

    @Override
    public SpellTrait as(String alias) {
        return new SpellTrait(DSL.name(alias), this);
    }

    @Override
    public SpellTrait as(Name alias) {
        return new SpellTrait(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpellTrait rename(String name) {
        return new SpellTrait(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpellTrait rename(Name name) {
        return new SpellTrait(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
