/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables;


import ai.ragu.charactermanager.jooq.Keys;
import ai.ragu.charactermanager.jooq.Public;
import ai.ragu.charactermanager.jooq.tables.records.WeaponMaterialRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WeaponMaterial extends TableImpl<WeaponMaterialRecord> {

    private static final long serialVersionUID = -1978300669;

    /**
     * The reference instance of <code>public.weapon_material</code>
     */
    public static final WeaponMaterial WEAPON_MATERIAL = new WeaponMaterial();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WeaponMaterialRecord> getRecordType() {
        return WeaponMaterialRecord.class;
    }

    /**
     * The column <code>public.weapon_material.id</code>.
     */
    public final TableField<WeaponMaterialRecord, String> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.weapon_material.name</code>.
     */
    public final TableField<WeaponMaterialRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.weapon_material.level</code>.
     */
    public final TableField<WeaponMaterialRecord, Integer> LEVEL = createField(DSL.name("level"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.weapon_material.reduces_bulk</code>.
     */
    public final TableField<WeaponMaterialRecord, String> REDUCES_BULK = createField(DSL.name("reduces_bulk"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.weapon_material.base</code>.
     */
    public final TableField<WeaponMaterialRecord, Integer> BASE = createField(DSL.name("base"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.weapon_material.description</code>.
     */
    public final TableField<WeaponMaterialRecord, String> DESCRIPTION = createField(DSL.name("description"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.weapon_material.src</code>.
     */
    public final TableField<WeaponMaterialRecord, String> SRC = createField(DSL.name("src"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.weapon_material.url</code>.
     */
    public final TableField<WeaponMaterialRecord, String> URL = createField(DSL.name("url"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.weapon_material</code> table reference
     */
    public WeaponMaterial() {
        this(DSL.name("weapon_material"), null);
    }

    /**
     * Create an aliased <code>public.weapon_material</code> table reference
     */
    public WeaponMaterial(String alias) {
        this(DSL.name(alias), WEAPON_MATERIAL);
    }

    /**
     * Create an aliased <code>public.weapon_material</code> table reference
     */
    public WeaponMaterial(Name alias) {
        this(alias, WEAPON_MATERIAL);
    }

    private WeaponMaterial(Name alias, Table<WeaponMaterialRecord> aliased) {
        this(alias, aliased, null);
    }

    private WeaponMaterial(Name alias, Table<WeaponMaterialRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> WeaponMaterial(Table<O> child, ForeignKey<O, WeaponMaterialRecord> key) {
        super(child, key, WEAPON_MATERIAL);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<WeaponMaterialRecord> getPrimaryKey() {
        return Keys.WEAPON_MATERIAL_PKEY;
    }

    @Override
    public List<UniqueKey<WeaponMaterialRecord>> getKeys() {
        return Arrays.<UniqueKey<WeaponMaterialRecord>>asList(Keys.WEAPON_MATERIAL_PKEY);
    }

    @Override
    public List<ForeignKey<WeaponMaterialRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<WeaponMaterialRecord, ?>>asList(Keys.WEAPON_MATERIAL__WEAPON_MATERIAL_SRC_FKEY);
    }

    public RulesSource rulesSource() {
        return new RulesSource(this, Keys.WEAPON_MATERIAL__WEAPON_MATERIAL_SRC_FKEY);
    }

    @Override
    public WeaponMaterial as(String alias) {
        return new WeaponMaterial(DSL.name(alias), this);
    }

    @Override
    public WeaponMaterial as(Name alias) {
        return new WeaponMaterial(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WeaponMaterial rename(String name) {
        return new WeaponMaterial(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WeaponMaterial rename(Name name) {
        return new WeaponMaterial(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, Integer, String, Integer, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
