/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables;


import ai.ragu.charactermanager.jooq.Keys;
import ai.ragu.charactermanager.jooq.Public;
import ai.ragu.charactermanager.jooq.tables.records.WeaponTraitRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WeaponTrait extends TableImpl<WeaponTraitRecord> {

    private static final long serialVersionUID = 473431496;

    /**
     * The reference instance of <code>public.weapon_trait</code>
     */
    public static final WeaponTrait WEAPON_TRAIT = new WeaponTrait();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WeaponTraitRecord> getRecordType() {
        return WeaponTraitRecord.class;
    }

    /**
     * The column <code>public.weapon_trait.weapon_id</code>.
     */
    public final TableField<WeaponTraitRecord, String> WEAPON_ID = createField(DSL.name("weapon_id"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.weapon_trait.trait</code>.
     */
    public final TableField<WeaponTraitRecord, String> TRAIT = createField(DSL.name("trait"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * Create a <code>public.weapon_trait</code> table reference
     */
    public WeaponTrait() {
        this(DSL.name("weapon_trait"), null);
    }

    /**
     * Create an aliased <code>public.weapon_trait</code> table reference
     */
    public WeaponTrait(String alias) {
        this(DSL.name(alias), WEAPON_TRAIT);
    }

    /**
     * Create an aliased <code>public.weapon_trait</code> table reference
     */
    public WeaponTrait(Name alias) {
        this(alias, WEAPON_TRAIT);
    }

    private WeaponTrait(Name alias, Table<WeaponTraitRecord> aliased) {
        this(alias, aliased, null);
    }

    private WeaponTrait(Name alias, Table<WeaponTraitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> WeaponTrait(Table<O> child, ForeignKey<O, WeaponTraitRecord> key) {
        super(child, key, WEAPON_TRAIT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<WeaponTraitRecord> getPrimaryKey() {
        return Keys.WEAPON_TRAIT_PKEY;
    }

    @Override
    public List<UniqueKey<WeaponTraitRecord>> getKeys() {
        return Arrays.<UniqueKey<WeaponTraitRecord>>asList(Keys.WEAPON_TRAIT_PKEY);
    }

    @Override
    public List<ForeignKey<WeaponTraitRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<WeaponTraitRecord, ?>>asList(Keys.WEAPON_TRAIT__WEAPON_TRAIT_WEAPON_ID_FKEY);
    }

    public Weapon weapon() {
        return new Weapon(this, Keys.WEAPON_TRAIT__WEAPON_TRAIT_WEAPON_ID_FKEY);
    }

    @Override
    public WeaponTrait as(String alias) {
        return new WeaponTrait(DSL.name(alias), this);
    }

    @Override
    public WeaponTrait as(Name alias) {
        return new WeaponTrait(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WeaponTrait rename(String name) {
        return new WeaponTrait(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WeaponTrait rename(Name name) {
        return new WeaponTrait(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
