/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq.tables;


import ai.ragu.charactermanager.jooq.Keys;
import ai.ragu.charactermanager.jooq.Public;
import ai.ragu.charactermanager.jooq.tables.records.WearableItemTraitRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WearableItemTrait extends TableImpl<WearableItemTraitRecord> {

    private static final long serialVersionUID = 2028385842;

    /**
     * The reference instance of <code>public.wearable_item_trait</code>
     */
    public static final WearableItemTrait WEARABLE_ITEM_TRAIT = new WearableItemTrait();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WearableItemTraitRecord> getRecordType() {
        return WearableItemTraitRecord.class;
    }

    /**
     * The column <code>public.wearable_item_trait.wearable_item_id</code>.
     */
    public final TableField<WearableItemTraitRecord, String> WEARABLE_ITEM_ID = createField(DSL.name("wearable_item_id"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.wearable_item_trait.trait</code>.
     */
    public final TableField<WearableItemTraitRecord, String> TRAIT = createField(DSL.name("trait"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * Create a <code>public.wearable_item_trait</code> table reference
     */
    public WearableItemTrait() {
        this(DSL.name("wearable_item_trait"), null);
    }

    /**
     * Create an aliased <code>public.wearable_item_trait</code> table reference
     */
    public WearableItemTrait(String alias) {
        this(DSL.name(alias), WEARABLE_ITEM_TRAIT);
    }

    /**
     * Create an aliased <code>public.wearable_item_trait</code> table reference
     */
    public WearableItemTrait(Name alias) {
        this(alias, WEARABLE_ITEM_TRAIT);
    }

    private WearableItemTrait(Name alias, Table<WearableItemTraitRecord> aliased) {
        this(alias, aliased, null);
    }

    private WearableItemTrait(Name alias, Table<WearableItemTraitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> WearableItemTrait(Table<O> child, ForeignKey<O, WearableItemTraitRecord> key) {
        super(child, key, WEARABLE_ITEM_TRAIT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<WearableItemTraitRecord> getPrimaryKey() {
        return Keys.WEARABLE_ITEM_TRAIT_PKEY;
    }

    @Override
    public List<UniqueKey<WearableItemTraitRecord>> getKeys() {
        return Arrays.<UniqueKey<WearableItemTraitRecord>>asList(Keys.WEARABLE_ITEM_TRAIT_PKEY);
    }

    @Override
    public List<ForeignKey<WearableItemTraitRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<WearableItemTraitRecord, ?>>asList(Keys.WEARABLE_ITEM_TRAIT__WEARABLE_ITEM_TRAIT_WEARABLE_ITEM_ID_FKEY);
    }

    public WearableItem wearableItem() {
        return new WearableItem(this, Keys.WEARABLE_ITEM_TRAIT__WEARABLE_ITEM_TRAIT_WEARABLE_ITEM_ID_FKEY);
    }

    @Override
    public WearableItemTrait as(String alias) {
        return new WearableItemTrait(DSL.name(alias), this);
    }

    @Override
    public WearableItemTrait as(Name alias) {
        return new WearableItemTrait(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WearableItemTrait rename(String name) {
        return new WearableItemTrait(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WearableItemTrait rename(Name name) {
        return new WearableItemTrait(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
