/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq;


import ai.ragu.charactermanager.jooq.tables.AbilityScore;
import ai.ragu.charactermanager.jooq.tables.AlchemistResearchField;
import ai.ragu.charactermanager.jooq.tables.Ancestry;
import ai.ragu.charactermanager.jooq.tables.AncestryAbilityBoosts;
import ai.ragu.charactermanager.jooq.tables.AncestryAbilityFlaws;
import ai.ragu.charactermanager.jooq.tables.AncestryLanguage;
import ai.ragu.charactermanager.jooq.tables.AncestryTrait;
import ai.ragu.charactermanager.jooq.tables.Armor;
import ai.ragu.charactermanager.jooq.tables.ArmorMaterial;
import ai.ragu.charactermanager.jooq.tables.ArmorTrait;
import ai.ragu.charactermanager.jooq.tables.Background;
import ai.ragu.charactermanager.jooq.tables.Clazz;
import ai.ragu.charactermanager.jooq.tables.CompanionItem;
import ai.ragu.charactermanager.jooq.tables.CompanionItemSkillBonus;
import ai.ragu.charactermanager.jooq.tables.CompanionItemTrait;
import ai.ragu.charactermanager.jooq.tables.Condition;
import ai.ragu.charactermanager.jooq.tables.CreatureSize;
import ai.ragu.charactermanager.jooq.tables.Feat;
import ai.ragu.charactermanager.jooq.tables.FeatAbilityScoreRequirement;
import ai.ragu.charactermanager.jooq.tables.FeatAnimalCompanionRequirement;
import ai.ragu.charactermanager.jooq.tables.FeatFamiliarRequirement;
import ai.ragu.charactermanager.jooq.tables.FeatFeatRequirement;
import ai.ragu.charactermanager.jooq.tables.FeatMagicRequirement;
import ai.ragu.charactermanager.jooq.tables.FeatSkillRequirement;
import ai.ragu.charactermanager.jooq.tables.FeatSpecialRequirement;
import ai.ragu.charactermanager.jooq.tables.FeatTrait;
import ai.ragu.charactermanager.jooq.tables.HellknightOrder;
import ai.ragu.charactermanager.jooq.tables.Item;
import ai.ragu.charactermanager.jooq.tables.ItemTrait;
import ai.ragu.charactermanager.jooq.tables.Language;
import ai.ragu.charactermanager.jooq.tables.LanguageCategory;
import ai.ragu.charactermanager.jooq.tables.MagicArmor;
import ai.ragu.charactermanager.jooq.tables.MagicArmorTrait;
import ai.ragu.charactermanager.jooq.tables.MagicWeapon;
import ai.ragu.charactermanager.jooq.tables.MagicWeaponTrait;
import ai.ragu.charactermanager.jooq.tables.PetAbility;
import ai.ragu.charactermanager.jooq.tables.PetAnimal;
import ai.ragu.charactermanager.jooq.tables.PetSpecialisation;
import ai.ragu.charactermanager.jooq.tables.RulesSource;
import ai.ragu.charactermanager.jooq.tables.Shield;
import ai.ragu.charactermanager.jooq.tables.ShieldTrait;
import ai.ragu.charactermanager.jooq.tables.Skill;
import ai.ragu.charactermanager.jooq.tables.SkillAction;
import ai.ragu.charactermanager.jooq.tables.SkillActionKeySkill;
import ai.ragu.charactermanager.jooq.tables.SkillActionTrait;
import ai.ragu.charactermanager.jooq.tables.Special;
import ai.ragu.charactermanager.jooq.tables.SpecialTrait;
import ai.ragu.charactermanager.jooq.tables.Spell;
import ai.ragu.charactermanager.jooq.tables.SpellList;
import ai.ragu.charactermanager.jooq.tables.SpellListItem;
import ai.ragu.charactermanager.jooq.tables.SpellTrait;
import ai.ragu.charactermanager.jooq.tables.SpellsBloodline;
import ai.ragu.charactermanager.jooq.tables.SpellsDomain;
import ai.ragu.charactermanager.jooq.tables.TrainingLevel;
import ai.ragu.charactermanager.jooq.tables.Weapon;
import ai.ragu.charactermanager.jooq.tables.WeaponMaterial;
import ai.ragu.charactermanager.jooq.tables.WeaponTrait;
import ai.ragu.charactermanager.jooq.tables.WearableItem;
import ai.ragu.charactermanager.jooq.tables.WearableItemTrait;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1773184938;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.ability_score</code>.
     */
    public final AbilityScore ABILITY_SCORE = AbilityScore.ABILITY_SCORE;

    /**
     * The table <code>public.alchemist_research_field</code>.
     */
    public final AlchemistResearchField ALCHEMIST_RESEARCH_FIELD = AlchemistResearchField.ALCHEMIST_RESEARCH_FIELD;

    /**
     * The table <code>public.ancestry</code>.
     */
    public final Ancestry ANCESTRY = Ancestry.ANCESTRY;

    /**
     * The table <code>public.ancestry_ability_boosts</code>.
     */
    public final AncestryAbilityBoosts ANCESTRY_ABILITY_BOOSTS = AncestryAbilityBoosts.ANCESTRY_ABILITY_BOOSTS;

    /**
     * The table <code>public.ancestry_ability_flaws</code>.
     */
    public final AncestryAbilityFlaws ANCESTRY_ABILITY_FLAWS = AncestryAbilityFlaws.ANCESTRY_ABILITY_FLAWS;

    /**
     * The table <code>public.ancestry_language</code>.
     */
    public final AncestryLanguage ANCESTRY_LANGUAGE = AncestryLanguage.ANCESTRY_LANGUAGE;

    /**
     * The table <code>public.ancestry_trait</code>.
     */
    public final AncestryTrait ANCESTRY_TRAIT = AncestryTrait.ANCESTRY_TRAIT;

    /**
     * The table <code>public.armor</code>.
     */
    public final Armor ARMOR = Armor.ARMOR;

    /**
     * The table <code>public.armor_material</code>.
     */
    public final ArmorMaterial ARMOR_MATERIAL = ArmorMaterial.ARMOR_MATERIAL;

    /**
     * The table <code>public.armor_trait</code>.
     */
    public final ArmorTrait ARMOR_TRAIT = ArmorTrait.ARMOR_TRAIT;

    /**
     * The table <code>public.background</code>.
     */
    public final Background BACKGROUND = Background.BACKGROUND;

    /**
     * The table <code>public.clazz</code>.
     */
    public final Clazz CLAZZ = Clazz.CLAZZ;

    /**
     * The table <code>public.companion_item</code>.
     */
    public final CompanionItem COMPANION_ITEM = CompanionItem.COMPANION_ITEM;

    /**
     * The table <code>public.companion_item_skill_bonus</code>.
     */
    public final CompanionItemSkillBonus COMPANION_ITEM_SKILL_BONUS = CompanionItemSkillBonus.COMPANION_ITEM_SKILL_BONUS;

    /**
     * The table <code>public.companion_item_trait</code>.
     */
    public final CompanionItemTrait COMPANION_ITEM_TRAIT = CompanionItemTrait.COMPANION_ITEM_TRAIT;

    /**
     * The table <code>public.condition</code>.
     */
    public final Condition CONDITION = Condition.CONDITION;

    /**
     * The table <code>public.creature_size</code>.
     */
    public final CreatureSize CREATURE_SIZE = CreatureSize.CREATURE_SIZE;

    /**
     * The table <code>public.feat</code>.
     */
    public final Feat FEAT = Feat.FEAT;

    /**
     * The table <code>public.feat_ability_score_requirement</code>.
     */
    public final FeatAbilityScoreRequirement FEAT_ABILITY_SCORE_REQUIREMENT = FeatAbilityScoreRequirement.FEAT_ABILITY_SCORE_REQUIREMENT;

    /**
     * The table <code>public.feat_animal_companion_requirement</code>.
     */
    public final FeatAnimalCompanionRequirement FEAT_ANIMAL_COMPANION_REQUIREMENT = FeatAnimalCompanionRequirement.FEAT_ANIMAL_COMPANION_REQUIREMENT;

    /**
     * The table <code>public.feat_familiar_requirement</code>.
     */
    public final FeatFamiliarRequirement FEAT_FAMILIAR_REQUIREMENT = FeatFamiliarRequirement.FEAT_FAMILIAR_REQUIREMENT;

    /**
     * The table <code>public.feat_feat_requirement</code>.
     */
    public final FeatFeatRequirement FEAT_FEAT_REQUIREMENT = FeatFeatRequirement.FEAT_FEAT_REQUIREMENT;

    /**
     * The table <code>public.feat_magic_requirement</code>.
     */
    public final FeatMagicRequirement FEAT_MAGIC_REQUIREMENT = FeatMagicRequirement.FEAT_MAGIC_REQUIREMENT;

    /**
     * The table <code>public.feat_skill_requirement</code>.
     */
    public final FeatSkillRequirement FEAT_SKILL_REQUIREMENT = FeatSkillRequirement.FEAT_SKILL_REQUIREMENT;

    /**
     * The table <code>public.feat_special_requirement</code>.
     */
    public final FeatSpecialRequirement FEAT_SPECIAL_REQUIREMENT = FeatSpecialRequirement.FEAT_SPECIAL_REQUIREMENT;

    /**
     * The table <code>public.feat_trait</code>.
     */
    public final FeatTrait FEAT_TRAIT = FeatTrait.FEAT_TRAIT;

    /**
     * The table <code>public.hellknight_order</code>.
     */
    public final HellknightOrder HELLKNIGHT_ORDER = HellknightOrder.HELLKNIGHT_ORDER;

    /**
     * The table <code>public.item</code>.
     */
    public final Item ITEM = Item.ITEM;

    /**
     * The table <code>public.item_trait</code>.
     */
    public final ItemTrait ITEM_TRAIT = ItemTrait.ITEM_TRAIT;

    /**
     * The table <code>public.language</code>.
     */
    public final Language LANGUAGE = Language.LANGUAGE;

    /**
     * The table <code>public.language_category</code>.
     */
    public final LanguageCategory LANGUAGE_CATEGORY = LanguageCategory.LANGUAGE_CATEGORY;

    /**
     * The table <code>public.magic_armor</code>.
     */
    public final MagicArmor MAGIC_ARMOR = MagicArmor.MAGIC_ARMOR;

    /**
     * The table <code>public.magic_armor_trait</code>.
     */
    public final MagicArmorTrait MAGIC_ARMOR_TRAIT = MagicArmorTrait.MAGIC_ARMOR_TRAIT;

    /**
     * The table <code>public.magic_weapon</code>.
     */
    public final MagicWeapon MAGIC_WEAPON = MagicWeapon.MAGIC_WEAPON;

    /**
     * The table <code>public.magic_weapon_trait</code>.
     */
    public final MagicWeaponTrait MAGIC_WEAPON_TRAIT = MagicWeaponTrait.MAGIC_WEAPON_TRAIT;

    /**
     * The table <code>public.pet_ability</code>.
     */
    public final PetAbility PET_ABILITY = PetAbility.PET_ABILITY;

    /**
     * The table <code>public.pet_animal</code>.
     */
    public final PetAnimal PET_ANIMAL = PetAnimal.PET_ANIMAL;

    /**
     * The table <code>public.pet_specialisation</code>.
     */
    public final PetSpecialisation PET_SPECIALISATION = PetSpecialisation.PET_SPECIALISATION;

    /**
     * The table <code>public.rules_source</code>.
     */
    public final RulesSource RULES_SOURCE = RulesSource.RULES_SOURCE;

    /**
     * The table <code>public.shield</code>.
     */
    public final Shield SHIELD = Shield.SHIELD;

    /**
     * The table <code>public.shield_trait</code>.
     */
    public final ShieldTrait SHIELD_TRAIT = ShieldTrait.SHIELD_TRAIT;

    /**
     * The table <code>public.skill</code>.
     */
    public final Skill SKILL = Skill.SKILL;

    /**
     * The table <code>public.skill_action</code>.
     */
    public final SkillAction SKILL_ACTION = SkillAction.SKILL_ACTION;

    /**
     * The table <code>public.skill_action_key_skill</code>.
     */
    public final SkillActionKeySkill SKILL_ACTION_KEY_SKILL = SkillActionKeySkill.SKILL_ACTION_KEY_SKILL;

    /**
     * The table <code>public.skill_action_trait</code>.
     */
    public final SkillActionTrait SKILL_ACTION_TRAIT = SkillActionTrait.SKILL_ACTION_TRAIT;

    /**
     * The table <code>public.special</code>.
     */
    public final Special SPECIAL = Special.SPECIAL;

    /**
     * The table <code>public.special_trait</code>.
     */
    public final SpecialTrait SPECIAL_TRAIT = SpecialTrait.SPECIAL_TRAIT;

    /**
     * The table <code>public.spell</code>.
     */
    public final Spell SPELL = Spell.SPELL;

    /**
     * The table <code>public.spell_list</code>.
     */
    public final SpellList SPELL_LIST = SpellList.SPELL_LIST;

    /**
     * The table <code>public.spell_list_item</code>.
     */
    public final SpellListItem SPELL_LIST_ITEM = SpellListItem.SPELL_LIST_ITEM;

    /**
     * The table <code>public.spell_trait</code>.
     */
    public final SpellTrait SPELL_TRAIT = SpellTrait.SPELL_TRAIT;

    /**
     * The table <code>public.spells_bloodline</code>.
     */
    public final SpellsBloodline SPELLS_BLOODLINE = SpellsBloodline.SPELLS_BLOODLINE;

    /**
     * The table <code>public.spells_domain</code>.
     */
    public final SpellsDomain SPELLS_DOMAIN = SpellsDomain.SPELLS_DOMAIN;

    /**
     * The table <code>public.training_level</code>.
     */
    public final TrainingLevel TRAINING_LEVEL = TrainingLevel.TRAINING_LEVEL;

    /**
     * The table <code>public.weapon</code>.
     */
    public final Weapon WEAPON = Weapon.WEAPON;

    /**
     * The table <code>public.weapon_material</code>.
     */
    public final WeaponMaterial WEAPON_MATERIAL = WeaponMaterial.WEAPON_MATERIAL;

    /**
     * The table <code>public.weapon_trait</code>.
     */
    public final WeaponTrait WEAPON_TRAIT = WeaponTrait.WEAPON_TRAIT;

    /**
     * The table <code>public.wearable_item</code>.
     */
    public final WearableItem WEARABLE_ITEM = WearableItem.WEARABLE_ITEM;

    /**
     * The table <code>public.wearable_item_trait</code>.
     */
    public final WearableItemTrait WEARABLE_ITEM_TRAIT = WearableItemTrait.WEARABLE_ITEM_TRAIT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.FEAT_SPECIAL_REQUIREMENT_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            AbilityScore.ABILITY_SCORE,
            AlchemistResearchField.ALCHEMIST_RESEARCH_FIELD,
            Ancestry.ANCESTRY,
            AncestryAbilityBoosts.ANCESTRY_ABILITY_BOOSTS,
            AncestryAbilityFlaws.ANCESTRY_ABILITY_FLAWS,
            AncestryLanguage.ANCESTRY_LANGUAGE,
            AncestryTrait.ANCESTRY_TRAIT,
            Armor.ARMOR,
            ArmorMaterial.ARMOR_MATERIAL,
            ArmorTrait.ARMOR_TRAIT,
            Background.BACKGROUND,
            Clazz.CLAZZ,
            CompanionItem.COMPANION_ITEM,
            CompanionItemSkillBonus.COMPANION_ITEM_SKILL_BONUS,
            CompanionItemTrait.COMPANION_ITEM_TRAIT,
            Condition.CONDITION,
            CreatureSize.CREATURE_SIZE,
            Feat.FEAT,
            FeatAbilityScoreRequirement.FEAT_ABILITY_SCORE_REQUIREMENT,
            FeatAnimalCompanionRequirement.FEAT_ANIMAL_COMPANION_REQUIREMENT,
            FeatFamiliarRequirement.FEAT_FAMILIAR_REQUIREMENT,
            FeatFeatRequirement.FEAT_FEAT_REQUIREMENT,
            FeatMagicRequirement.FEAT_MAGIC_REQUIREMENT,
            FeatSkillRequirement.FEAT_SKILL_REQUIREMENT,
            FeatSpecialRequirement.FEAT_SPECIAL_REQUIREMENT,
            FeatTrait.FEAT_TRAIT,
            HellknightOrder.HELLKNIGHT_ORDER,
            Item.ITEM,
            ItemTrait.ITEM_TRAIT,
            Language.LANGUAGE,
            LanguageCategory.LANGUAGE_CATEGORY,
            MagicArmor.MAGIC_ARMOR,
            MagicArmorTrait.MAGIC_ARMOR_TRAIT,
            MagicWeapon.MAGIC_WEAPON,
            MagicWeaponTrait.MAGIC_WEAPON_TRAIT,
            PetAbility.PET_ABILITY,
            PetAnimal.PET_ANIMAL,
            PetSpecialisation.PET_SPECIALISATION,
            RulesSource.RULES_SOURCE,
            Shield.SHIELD,
            ShieldTrait.SHIELD_TRAIT,
            Skill.SKILL,
            SkillAction.SKILL_ACTION,
            SkillActionKeySkill.SKILL_ACTION_KEY_SKILL,
            SkillActionTrait.SKILL_ACTION_TRAIT,
            Special.SPECIAL,
            SpecialTrait.SPECIAL_TRAIT,
            Spell.SPELL,
            SpellList.SPELL_LIST,
            SpellListItem.SPELL_LIST_ITEM,
            SpellTrait.SPELL_TRAIT,
            SpellsBloodline.SPELLS_BLOODLINE,
            SpellsDomain.SPELLS_DOMAIN,
            TrainingLevel.TRAINING_LEVEL,
            Weapon.WEAPON,
            WeaponMaterial.WEAPON_MATERIAL,
            WeaponTrait.WEAPON_TRAIT,
            WearableItem.WEARABLE_ITEM,
            WearableItemTrait.WEARABLE_ITEM_TRAIT);
    }
}
