/*
 * This file is generated by jOOQ.
 */
package ai.ragu.charactermanager.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.feat_special_requirement_id_seq</code>
     */
    public static final Sequence<Integer> FEAT_SPECIAL_REQUIREMENT_ID_SEQ = Internal.createSequence("feat_special_requirement_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
